### ISSUE TITLE
instructions unclear

### ISSUE THREAD

**Issue by matticas** [DavidFW1960/bom-weather-card#10]
Hi David;
These instructions are convoluted and very difficult to follow.  2 nights attempting to get this working and no success.  Would it be possible to show proper examples of what you are entering into config.yaml / ui-lovelace.yaml in clear instructions?  I've tried multiple combinations after "installing" this from HACS, yet nothing is working and no entities appearing.  Something is missing yet after reading your instructions repeatedly I can not work out what it is.
Thanks

**Comment by neddytheman** [comment]
Hey - I am having the same problem!!!

Mine is coming up with custom element not found.

**Comment by matticas** [comment]
Hi Neddy;
Since typing, I've got the card up.  Had to dig through the code.  Melbourne on the website is IDV609xx something.   But if you dig through the /config/custom_components/bom_forecast/sensor.py  it contains a list of the useable cities and the correct ID value.  If you enter that value, you should start to see entities at least.
I'm working on the Icons, the downloadable ZIP has all the animated filenames wrong.

**Comment by DavidFW1960** [comment]
> I'm working on the Icons, the downloadable ZIP has all the animated filenames wrong.

No it doesn't

**Comment by matticas** [comment]
Yes, yes it does David.  Use the Darksky icons from his source works.  Yours have the wrong filenames - have you checked your repo zip download filenames?  
I had to dig through the darksky code and yours to piece it together.
If anyone actually wants help on the topic - please feel free to contact me!  David is clearly to arrogant to look into it!

**Comment by DavidFW1960** [comment]
No actually. There are a LOT of people using this repo and these files. Just FWIW, the original card which maybe you are using has been changed in this fork. I guarantee you that the icons in my zip file correspond with the conditions and references to icons in the card.

If you want to talk about arrogance look at your first post.

I have provided a full weather.yaml package as an example as well as a full lovelace example file in the repo. I guess you missed those before you embarked on your rant.

I have also helped countless people get this working.

If you spent 2 days and couldn't make it work and didn't ask for help but then accuse me of faulty/incomplete instructions and wrong files.... well that is on you.

**Comment by DavidFW1960** [comment]
> But if you dig through the /config/custom_components/bom_forecast/sensor.py it contains a list of the useable cities and the correct ID value

or alternatively, just FOLLOW THE INSTRUCTIONS to get the BOM code from the BOM site. I even provided a screenshot and full instructions showing how to find the right code.

**Comment by DavidFW1960** [comment]
> Mine is coming up with custom element not found.

Perhaps a caching issue. Have you cleared your cache? (in Chrome F12 and right click the refresh button select Clear Cache and Hard reload i think it says) If you still have an issue, open a new issue here or post on the thread on the forum.
