### ISSUE TITLE
Ability to make certain sensors come from different providers?

### ISSUE THREAD

**Issue by snarlingllama** [DavidFW1960/bom-weather-card#100]
I am very interested in this but had a few questions.

1. Can I point different providers as the source data for some of the sensors?
2. Can I change the sensors displayed in favor of other sensors?

For example, I use several sources for weather data: openweather, local ecowitt, stormglass, and blitzortung. All of which I have favorite sensors from. I would like to add a combination of these providers.

Is this possible?

**Comment by DavidFW1960** [comment]
Anything is possible with this card. You can pass ANY HA entity you want from any provider for the card to display. There are even custom slots so you define the mdi icon, the entity and unit. This is not locked to any provider even though it was originally written for Darksky and then the Australian BOM integration it can be anything. We are also working on a major update that will have GUI configuration and many more options but fully compatible with the config for this card. You can checkout the Alpha version of that here https://github.com/Makin-Things/makin-things-weather-card
This is what mine currently looks like
![image](https://user-images.githubusercontent.com/36390762/174415221-b5de8c50-e9e6-4320-a8a9-3f22c9ea8b80.png)

That url for the card can be added as a manual repo in HACS too

**Comment by snarlingllama** [comment]
Greatly appreciate your response! This was exactly what I needed.
