### ISSUE TITLE
when unpkg.com is misbehaving, the bom card won't render.

### ISSUE THREAD

**Issue by davidmonro** [DavidFW1960/bom-weather-card#101]
Over the last few days, unpkg.com seems to have been having issues serving the lit-element code (using the firefox network monitoring shows that server returning http 520 status, which would indicate cloudflare is getting bad responses from the origin server).

When this happens, the card completely fails to render with "custom element doesn't exist: bom-weather-card"

Perhaps the lit-element code could be included in the card install?

(I'd note that bom-weather-card seems to be the only card I'm using which depends on anything delivered from an external URL - this is a bit problematic as it means my kiosk machine needs to have access to the internet, rather than just access to my server).

**Comment by markusg1234** [comment]
Same issue here. Started today.

**Comment by hillbillypolenta** [comment]
While researching this, I note it has been an issue (unpkg) for a couple of years. With some discussion of using lit locally eg here - https://github.com/custom-cards/button-card/issues/43 - I tried to work from the examples given, unfortunately quickly hit my talent wall.

**Comment by DavidFW1960** [comment]
I hadn't seen any issues here but I am using the replacement card we are working on here https://github.com/Makin-Things/platinum-weather-card
That should work with the same configuration you currently use for my card.
I cannot duplicate this error on my card either. it's still working here. Which version do you run?

**Comment by peterhoe** [comment]
I saw it yesterday as well, for about 30 minutes.  Same goes for another custom card I use called circle sensor card which also uses litelement



Get Outlook for Android<https://aka.ms/ghei36>
________________________________
