### ISSUE TITLE
Daytime_high and daytime_low display values differently

### ISSUE THREAD

**Issue by SgtTacooo** [DavidFW1960/bom-weather-card#102]
Maybe this is just the way the BOM is reporting my local weather but I noticed that daytime_high shows n°C while daytime_low shows n °C (with a space between the float and the units). As someone who loves conformity on my dashboard it would be great if this minor thing could be fixed so all values show n°C (without the space).

**Comment by DavidFW1960** [comment]
I'm not seeing that here
![image](https://user-images.githubusercontent.com/36390762/182008509-8a9eff9d-875e-4714-b4a5-76a925b1df7e.png)
These are generally coming from a template sensor so I'd suggest checking the template.

**Comment by Potplanty** [comment]
That's strange. Your high also shows a space between the value and the unit. I've double checked the templates and I can't find any extra space that would be causing this. I also copied your templates from this project and just replaced the place names with my own ones. The original sensors for pulling values from also don't seem to be giving a trailing space after the values either.

**Comment by DavidFW1960** [comment]
Can you show your card config & the dev-tools screenshot of the entities.

**Comment by Potplanty** [comment]
Oh didn't realise this card was getting phased out. Thanks for letting me know, I've moved onto the Platinum card and it appears to be working as it should.

One other question - I'm using the official BOM integration and I'm getting an "unknown" value for the location_temp_min_0 sensor for the current day. The sensors for all following days are showing fine but this suddenly dropped its value earlier today despite still updating from BOM. Any idea why this might happen? I can still see the sensor under the BOM integration for my area.

**Comment by DavidFW1960** [comment]
Yes. BOM stops publishing it during the afternoon. That is why I use the average integration to show the actual minimum/maximum! This is all documented in the repo and reflected in the templates. There are new entities you can make use of in the new card too. This is what mine loks like:
![image](https://user-images.githubusercontent.com/36390762/182018206-d09163b6-e4d1-4de3-98f8-15473021c73c.jpeg)

**Comment by DavidFW1960** [comment]
See also my forecast minimum is NaN for the same reason. But actual is from average

**Comment by Potplanty** [comment]
Ahh great, thanks for that one. Guess I'll install the average component and use that instead.

**Comment by lionslair** [comment]
> Can you show your card config & the dev-tools screenshot of the entities. Also be aware this card is in the process of being replaced by https://github.com/Makin-Things/platinum-weather-card It is in HACS. It will work with the config for my card if you install it and change the card in lovelace

What is the ETA on the phase out. Only set this up yesterday

**Comment by DavidFW1960** [comment]
> What is the ETA on the phase out. Only set this up yesterday

No phase out as such. You can migrate whenever you want or stay on this card it's up to you. Many people have already migrated (including me). Simon and I have worked very closely on this.

**Comment by SgtTacooo** [comment]
I'll add that the migration is simple as can possibly be too. Keep all the same sensors, just pick the right ones on the GUI editor and away you go.
