### ISSUE TITLE
Increase overall scaling

### ISSUE THREAD

**Issue by Line-Noise** [DavidFW1960/bom-weather-card#103]
G'day!

Is it possible to scale the fonts and icons make them larger? If my weather card has lots of realestate on the screen I end up with a lot of whitespace:

![Screenshot_from_2022-08-09_09-15-36](https://user-images.githubusercontent.com/2012813/183530555-1d98eca1-dde3-4775-92a0-7588c543b1c6.png)

I've set `temp_font_size` and `summary_font_size` (`current_text_font_size` doesn't seem to change anything) but I'd like to change the size of all the other text and icons to improve readability from a distance.

In a perfect world it would scale automatically depending on the size of the card. In a less than perfect world there would be a single value to change to scale everything proportionally. In a not-so-great-but-still-better-than-today world there would be separate font configs for each element in the card.

Thanks!

**Comment by DavidFW1960** [comment]
You need to use card-mod to change other items. Also think about migrating to the new Platinum weather card here https://github.com/Makin-Things/platinum-weather-card also available in HACS
