### ISSUE TITLE
Authenticated depreciated

### ISSUE THREAD

**Issue by Electronlibre2012** [DavidFW1960/bom-weather-card#104]
hello @DavidFW1960

sorry to post here, dont know how to contact you...

You post your sensor for Authenticated custom component and now the comments are closed,

can you share your template sensor code please?

Thanks

**Comment by DavidFW1960** [comment]
see the thread on the forum you started. I did manually need to merge a PR that was closed before he deprecated the component. It may have had something to do with attributes. My running version of the component is here:
https://github.com/DavidFW1960/home-assistant/tree/master/custom_components/authenticated
