### ISSUE TITLE
Installation procedure problem

### ISSUE THREAD

**Issue by haps-basset** [DavidFW1960/bom-weather-card#105]
Hello
I have noticed your bom-wether-card for HA, and it looks lovely.  I followed your installation procedure, but the installation resource procedure hangs, please see the dump screen. 
Haps
![Screenshot 2022-11-07 182033](https://user-images.githubusercontent.com/20885804/200254888-f3324bab-6f99-4e5d-8785-707bde7f7215.png)

**Comment by DavidFW1960** [comment]
It's already a default repo you don't need to add it. You should be using the platinum weather card now anyway

**Comment by DavidFW1960** [comment]
It's also not an integration it's a lovelace card

**Comment by haps-basset** [comment]
Many thanks for clarification. Can you update the installation procedure?
Haps
