### ISSUE TITLE
BOM Integration

### ISSUE THREAD

**Issue by oneseventhree** [DavidFW1960/bom-weather-card#106]
Hi,

This seems like a great card!

I am just wondering how I can make it work with the BOM integration since all my information is under the sensor 'weather.melbourne'
do I have to make templates for all the entities needed to run:

```
type: custom:bom-weather-card
title: BOM Weather
entity_current_conditions: sensor.melbourne_short_text_0
entity_temperature: sensor.MAKE_TEMPLATE_SENSOR
entity_forecast_high_temp_1: sensor.MAKE_TEMPLATE_SENSOR
entity_forecast_high_temp_2: sensor.MAKE_TEMPLATE_SENSOR
entity_forecast_high_temp_3: sensor.MAKE_TEMPLATE_SENSOR
entity_forecast_high_temp_4: sensor.MAKE_TEMPLATE_SENSOR
entity_forecast_high_temp_5: sensor.MAKE_TEMPLATE_SENSOR
``

**Comment by DavidFW1960** [comment]
Yes you need templates for that. BUT you should use the new platinum weather card which will use the weather platform. The BOM integration should be creating all the real sensors as well as weather though

**Comment by oneseventhree** [comment]
> 

Thanks for the quick reply - wheres the new platinum weather card?

**Comment by oneseventhree** [comment]
> Yes you need templates for that. BUT you should use the new platinum weather card which will use the weather platform. The BOM integration should be creating all the real sensors as well as weather though

Thanks for the quick reply - where's the new platinum weather card? Is that the 'weather-forecast' card?
