### ISSUE TITLE
How do i configure another weather provider than BOM?

### ISSUE THREAD

**Issue by AfcaEric** [DavidFW1960/bom-weather-card#107]
So, i'm already having a really hard time understanding the configuration of this card, but i really like the look of it.
Now i understand this should work with any provider (like you said in the readme), but i have literally no idea what i should edit in the weather.yaml file. Do i really need to edit **EVERY** almost every line in weather.yaml to accomodate my own weather provider (OpenWeatherMap)?

**Comment by DavidFW1960** [comment]
Well the weather.yaml file is customised for my provider and the sensors my weather integration provides so yes.
But please also look for the platinum weather card which is a newer version of this card that you might find easier to configure
