### ISSUE TITLE
Clarification of directory structures for manual install in readme

### ISSUE THREAD

**Issue by kestrachern** [DavidFW1960/bom-weather-card#110]
Completing a manual install (I know this is suboptimal, but still, the documentation is there!), there are a couple of incomplete/possibly incorrect sections. Could these be updated/clarified?

1. `2. Add /local/bom-weather-card/bom-weather-card.js?v=o.89 type js to resources.` (line 80). 
a. I think the directory `/local/bom-weather-card/` does not exist, unless the previous instruction to put `bom-weather-card.js` directly under `<config-dir>/www/` was incorrect? Should this be just `/local/bom-weather-card.js?v=0.89` ? 
b. Minor typo v=**o**.89 ?
c. For the newbies, could you clarify that adding to resources means put this in configuration.yaml under `lovelace: resources:`; or wherever it should be if that inference is incorrect!
3. Later on (line 155), it says to add `resources: - url: /local/custom_ui/bom-weather-card.js?v=0.1 type: module`. Are both required (`type: js` and `type: module`), or is one incorrect? Also again, I do not think the directory `/local/custom_ui/` exists, unless instruction to create it was missing?

Having issues getting the card to show up, hoping that this clarification will assist.
Thanks

**Comment by DavidFW1960** [comment]
Feel free to submit a PR to change this but be aware this card is superseded by the new Platinum Weather card now.

**Comment by kestrachern** [comment]
Thanks, didn't see that, will check it out. Might also then be worth adding the superseded info that at the top of the readme! Cheers.
