### ISSUE TITLE
Custom element doesn't exist: bom-weather-card.

### ISSUE THREAD

**Issue by nthulke** [DavidFW1960/bom-weather-card#111]
Had this working for a long time, over a year and today it started showing this:

![image](https://user-images.githubusercontent.com/69140718/225475912-5384afc9-2ab4-4d1a-ba91-8f215595592b.png)

I did an update about 4 days ago to 2023.3.3 but saw no issues with this card after updating until today.

I have restarted the server and done ctrl ft reloads to see if it was that annoying cache issue, this did not resolve the issue.

**Comment by DavidFW1960** [comment]
I suggest switching to https://github.com/Makin-Things/platinum-weather-card - it is in HACS. it will import the configuration from this card and should 'just work'. This card is pretty much deprecated now.

**Comment by nthulke** [comment]
ok thanks, ill look at doing that!
