### ISSUE TITLE
'Fire' appears prefixed to entity_fire_danger_summary

### ISSUE THREAD

**Issue by stevearmitage** [DavidFW1960/bom-weather-card#12]
Hi,

I get the word 'Fire' in front of the summary information for fire danger summary

In the template tool: {{ states('sensor.bom_perth_forecast_fire_danger_summary') }}
Displays: Perth Coastal Plain: Low-Moderate, Perth Hills: Low-Moderate

In the card: 
entity_fire_danger_summary: sensor.bom_perth_forecast_fire_danger_summary
See the attached image for how it shows

<img width="453" alt="Screenshot 2020-05-04 at 13 04 36" src="https://user-images.githubusercontent.com/29444933/80937466-dbb1cf80-8e07-11ea-9e2e-a28e41b52e83.png">

Apart from that, this is a great card - thank you 👍

**Comment by DavidFW1960** [comment]
Yeah the card adds that to the front
![image](https://user-images.githubusercontent.com/36390762/81245147-9be12700-9057-11ea-9d85-f92e534a3180.png)
same as it adds UV to the front of the UV entity.
If it bothers you, you can edit the js file
Line 251
```
          fireDanger: "Fire"
```
Change to:
```
          fireDanger: ""
```
Should fix it. But you need to delete the .gz file HACS creates if you do that. You might need to refresh a few times as well. Any update will overwrite it as well....

**Comment by stevearmitage** [comment]
Perfect. Thanks David.
Is there somewhere to add enhancement requests?
- I.d like to have wind_gust_speed - shown in brackets next to wind speed if it's set

e.g. NNE 7 km/h (Gust: 14km/h)

Cheers,
Steve

**Comment by DavidFW1960** [comment]
Like this?
![image](https://user-images.githubusercontent.com/36390762/81254671-21bc9c80-906f-11ea-99f8-e7a50d01580b.png)
You can try it by setting HACS to Master and updating to Master.
When it works for a few days I can push it as a regular update.
Please give me feedback here if it works or not....
Good suggestion.
NOTE: add to lovelace:
```
entity_wind_gust: sensor.bom_gosford_wind_gust_kmh
```
Substituting your entity id for gosford of course

**Comment by stevearmitage** [comment]
Exactly! Thank you so much.
<img width="508" alt="Screenshot 2020-05-07 at 13 12 59" src="https://user-images.githubusercontent.com/29444933/81256933-87575b80-9064-11ea-9cd7-2a9b216f21e8.png">

Some more comments:
1. when I use a knot wind speed, it reports as km/h. Is it possible to support this?
2. For Perth, I often get a min temp of 'n/a' which displays as NaN in the screenshot. Not sure if it would be better to hide or leave as-is?

**Comment by DavidFW1960** [comment]
No can't support knots - I'd suggest a template sensor to convert to km/h
n/a means you haven't followed the instructions and added template sensor. BOM zeros out min/max once that has passed for the day so I recommend template sensors to fix
I'll look at the leading zeros..

**Comment by stevearmitage** [comment]
"BOM zeros out min/max once that has passed for the day so I recommend template sensors to fix"

It looks like in Perth, BOM put's n/a after the minimum temperature has passed
<img width="389" alt="Screenshot 2020-05-07 at 15 15 39" src="https://user-images.githubusercontent.com/29444933/81265422-a7434b00-9075-11ea-87b1-eccfdb931010.png">

As the Low temp is usually first thing in the morning, I've removed the low from the page as it wasn't adding value. I also realized id's used measured rain rather than forecasted rain for today in the card.
<img width="494" alt="Screenshot 2020-05-07 at 15 19 05" src="https://user-images.githubusercontent.com/29444933/81265704-2042a280-9076-11ea-934a-d76100d22d5b.png">

Thanks again for this great card.

**Comment by DavidFW1960** [comment]
Yes the rain one shows rainfall since 9AM for the current day. You can just pass a different HA sensor through. My BOM station always reports zero forecast for the current day.

For the minimum and maximum temperature like I said - use the provided template sensor. You can use either the statistics sensor to tell you the min/max temperature for the last 24 hours and it will put that in so the sensor doesn't show n/a. I use a custom_component - average which gives me the minimum and maximum temp since midnight. You will find the max one you are showing will also show n/a after around 2PM in the afternoon.... so try the template sensors - example provided in the templte yaml file.

Please do let me know if you see any errors or problems with the gust...

**Comment by DavidFW1960** [comment]
Hey Steve.. just an update. 0.72 will allow you to use knots (new slot option and entities to be parsed to card required see install into in info.md or readme)
I also fixed the leading zeros.

**Comment by stevearmitage** [comment]
I saw that in the latest update.
Thank you. 
It'll be treated in the 100km/h winds were expecting this week

> Hey Steve.. just an update. 0.72 will allow you to use knots (new slot option and entities to be parsed to card required see install into in info.md or readme)
> I also fixed the leading zeros.

**Comment by DavidFW1960** [comment]
100 km/h???? Where the hell are you? Bass Strait?

**Comment by stevearmitage** [comment]
I see another update came through.
Thanks for being very responsive and active with this component.

This wind is in Perth - just taken this screenshot!
<img width="485" alt="Screenshot 2020-05-25 at 09 28 38" src="https://user-images.githubusercontent.com/29444933/82770191-2f916080-9e6a-11ea-84e5-12071402d85a.png">

**Issue**
When i changed the value to a knot parameter, It did not change the units displayed
<img width="921" alt="Screenshot 2020-05-25 at 09 30 37" src="https://user-images.githubusercontent.com/29444933/82770251-6ff0de80-9e6a-11ea-938e-7ecd266a0758.png">
 
<img width="238" alt="Screenshot 2020-05-25 at 09 29 50" src="https://user-images.githubusercontent.com/29444933/82770250-6e271b00-9e6a-11ea-8cb3-655eb6656960.png">

**Enhancement**
I look at this on my mobile - when the 2 columns are made into 1, can you hide an 'empty' cell?
otherwise a gap is left.

**Comment by DavidFW1960** [comment]
Check that you added the options for knots. You need to parse 2 new entities to the card AND add a slot eg:
```
slot_l3: wind_kt
```
```
entity_wind_speed_kt: sensor.bom_gosford_wind_speed_kt
entity_wind_gust_kt: sensor.bom_gosford_wind_gust_kt
```

You can also set the slot to empty or remove. Remove should close up the gap.

**Comment by DavidFW1960** [comment]
ah I see...
Yeah no - you need to fill the LHS. The card doesn't know it's on a mobile.
Maybe remove the sun ones so one is on top of the other instead of adjacent? It's just that you are used to them being next to each other....
Or you can show windspeed as kt and km/h on different lines to fill the slots?

Never knew Perth was that windy.

**Comment by stevearmitage** [comment]
I win the Monday Numpty award - and Kts works beautifully now.
I also took your suggestion and added the kmh to fill the gap.

Thanks.

> Check that you added the options for knots. You need to parse 2 new entities to the card AND add a slot eg:
> 
> ```
> slot_l3: wind_kt
> ```
> 
> ```
> entity_wind_speed_kt: sensor.bom_gosford_wind_speed_kt
> entity_wind_gust_kt: sensor.bom_gosford_wind_gust_kt
> ```
> 
> You can also set the slot to empty or remove. Remove should close up the gap.

**Comment by DavidFW1960** [comment]
it's ok.... no one reads the docs/release notes lol
