### ISSUE TITLE
Current_Text being cropped

### ISSUE THREAD

**Issue by MightyMilster** [DavidFW1960/bom-weather-card#22]
Hi David.
Given, today my card was reporting "Morning Fog", I noticed for the first time that this field was not displaying correctly. The 2 "g" characters are being cropped. Almost to the point where they look like a "q". 
Which setting can I manipulate to give this field more depth. Perhaps it is the data below that is to tall and it is overlapping current_text. Not sure.

Thanks!

**Comment by DavidFW1960** [comment]
Wow!!!!!
Dude you're psychic. I just noticed that myself last night.
I just pushed 0.76a but have not made into a release yet.
If you use HACS, can you try master instead of 0.76. Verify in the console it's 0.76a and check what is happening and let me know?

**Comment by DavidFW1960** [comment]
It's funny... the example graphic on the main screen is showing the cropping as well but I'd never noticed it before!

**Comment by DavidFW1960** [comment]
closed via https://github.com/DavidFW1960/bom-weather-card/releases/tag/0.77

**Comment by MightyMilster** [comment]
haha. That is funny. I thought afterwards - oh I wonder if I should provide
a screenshot and then noticed your example graphic showed the cropping. And
you noticed that too. WFH must be sharpening our psychic powers! Thanks for
the updates!

**Comment by DavidFW1960** [comment]
I swear I never noticed it before which is odd because I am pedantic about that kind of thing.
I did make a new release as well. (in HACS)
