### ISSUE TITLE
Graphs not updating without refressh

### ISSUE THREAD

**Issue by theOzzieRat** [DavidFW1960/bom-weather-card#23]
Hi David,

Firstly I love what your work and I am pretty new to Home Assistant so still learning, but am a programmer (just not good at Python yet).

I have the graphs set up, but they only update when I do a refresh. of the page. Is this a bug or something I have configured wrongly.

Also the data provided by the core bom sensor code for observations is not that great. They are using data that only updates every 30 minutes, but the bom actually provide data every 10 minutes. I have an mqqt server hosted on google that pulls all that data and publishes it. I have had a look at creating a bom-mqqt integration but I am really not sure where to start. If you interested flick me an email and I'll share some stuff privately. (simon at makin-thing.com)

Cheers
Simon

**Comment by DavidFW1960** [comment]
Further to my email.. you can parse ANY sensor data to the card so if you have better data it will use that. I did reply via email and interested in your input. The card is set to update every 30 seconds (I think from memory)

**Comment by DavidFW1960** [comment]
Email bounced..

**Comment by theOzzieRat** [comment]
Sorry, can't type. simon at makin-things.com. Missed the 's'
