### ISSUE TITLE
'install' is deprecated, use 'async_install' instead

### ISSUE THREAD

**Issue by peter-ogden** [DavidFW1960/bom-weather-card#24]
Love your work. One small issue I noted when I upgraded to v0.78 today. I received the following warning in the log file (BTW, it appears to work fine):

Log Details (WARNING)
Logger: hacs.repository.plugin.DavidFW1960.bom-weather-card
Source: custom_components/hacs/repositories/helpers/methods/installation.py:17
First occurred: 12:59:19 (1 occurrences)
Last logged: 12:59:19

'install' is deprecated, use 'async_install' instead

**Comment by DavidFW1960** [comment]
That seems to be a HACS error. Are you running the latest version of HACS? This is not this card.

**Comment by peter-ogden** [comment]
Sorry, yes I am using the current version of HACS (1.1.0):
![image](https://user-images.githubusercontent.com/39589180/84347724-d2c1d400-abe5-11ea-96d1-fade474daad1.png)

**Comment by DavidFW1960** [comment]
See this issue on HACS repo
https://github.com/hacs/integration/issues/1320
As I said it's a HACS issue..
