### ISSUE TITLE
Feature request: semi transparent background

### ISSUE THREAD

**Issue by rasho6169** [DavidFW1960/bom-weather-card#25]
David, is there currently available a way to set background colour of BOM weather card to semi transparent.

**Comment by DavidFW1960** [comment]
There isn't an option for that in the card. All these are set by HA with the theme. You could try playing with card-mod?

**Comment by rasho6169** [comment]
![hasio-weather](https://user-images.githubusercontent.com/68669824/89517346-262e5800-d80c-11ea-97f7-2892bafbf97e.jpg)
Hi David, per your advise i installed card-mod via HACS. The attached jpeg is the end result. After install the following code was added at the end of your code in Lovelace UI.
        style: |
          ha-card {
            border: solid 1px rgba(100,100,100,0.8);
            background: rgba(255,255,255,0.6);
          }

please note indents: style: |  must line up with tab indent of your code ie
        tooltip_width: 110
        tooltips: true
        style: |
          ha-card {
            border: solid 1px rgba(100,100,100,0.8);
            background: rgba(255,255,255,0.6);
          }

The second jpeg is to demonstrate how opaque cards take away the visual aspect of backgrounds. First two card with transparency the other 3 cards no card-mod.
![hasio-overview](https://user-images.githubusercontent.com/68669824/89518996-4a8b3400-d80e-11ea-8457-de5f5583d671.jpg)

NB: background is from animated-background, another HACS install

Please address this post as solved

**Comment by DavidFW1960** [comment]
Nice!
Just one thing.. the fire danger is very long. I think there is a template sensor example in the docs to trim it down a bit... Up to you of course. My card looks like this.
![image](https://user-images.githubusercontent.com/36390762/89590368-173aba80-d88b-11ea-999c-54d0f7809b93.png)
(We don't have any fire danger in winter here it seems...)
The Perth BOM Fire has 2 regions and a Template sensor will help you to pick the appropriate one.
