### ISSUE TITLE
Configuration Help

### ISSUE THREAD

**Issue by x-Felix** [DavidFW1960/bom-weather-card#28]
I need some further instruction of setting this weather card up. 

I have setup bom forecast and using weather.yaml packages template all working as expected. However, have some difficulty to get frontend bom-weather-card properly displayed. 

I have installed HACS and installed Bom Weather Card through it. Also has weather icons downloaded extracted in the right path. 

In the Readme.md - Configuration - 2, for HACS installation. Where should I put resources and module type? If I add lines at the top of home dashboard - raw configuration editor, system will alert me to add configuration in lovelace UI configuration. 
So I go to Configuration - Lovelace Dashboards - Resources. I saw URL shows '/hacsfiles/bom-weather-card/bom-weather-card.js', Type shows 'JavaScript Module'. I have no way to change it type to 'module', the only option is 'Stylesheet'. 
If I change the URL 'hacsfiles' to /config/www/community', HACS will alert me this frontend bom-weather-card is not loaded. 

I assume JavaScript Module is the correct type. Then I go back to home page. Edit Dashboard, add card, manual, modify and paste content from bom-weather-card/lovelace.yaml but nothing shows up. 

Would you please suggest which step I may have missed? Thanks a lot.

**Comment by DavidFW1960** [comment]
HACS should setup the resources for you and you should leave it as hacsfiles  Are you using yaml or GUI for configuration?
/hacsfiles/bom-weather-card/bom-weather-card.js, Type shows 'JavaScript Module'. Is correct.

You might need to CTRL+R a few times in your browser to make it load correctly. If you press F12 in Chrome it should list the card and version in the console if it is loaded. You don't add the resources to the raw file.
You do need to add lovelace config for the card... using your entities of course (edit my example is the best way) Then add it in the GUI as a manual card

**Comment by x-Felix** [comment]
Thanks. 

Under Chrome, dev console, I saw one error. 

Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at HTMLElement.get current [as current] (bom-weather-card.js:414)
    at HTMLElement.render (bom-weather-card.js:26)
    at HTMLElement.update (app.75ee90d1.js:1)
    at HTMLElement.performUpdate (app.75ee90d1.js:1)
    at HTMLElement._enqueueUpdate (app.75ee90d1.js:1)

```
  get current() {
    var conditions = this._hass.states[this.config.entity_current_conditions].state;
```

Is this because some entry has no record?

**Comment by x-Felix** [comment]
I finally got it work. Cool.
It was actually some entries name wrong when replacing the template. 
As my location does not have a weather station, so I have to use a nearby station and name it differently. That results two different kind of bom entries, take time to get all entries aligned together. 
Thank you for your help.

**Comment by DavidFW1960** [comment]
Yeah if you parse through entities they have to exist. Glad you got it going.
