### ISSUE TITLE
The card is not displayed after update HA to 0.116

### ISSUE THREAD

**Issue by bieniu** [DavidFW1960/bom-weather-card#30]
After upgrade HA to 0.116.0 card is not displayed and there is an error in browser console:
```
Uncaught TypeError: Cannot read property 'childElementCount' of null
    at HTMLElement.updateValues (bom-weather-card.js:878)
    at HTMLElement.set hass [as hass] (bom-weather-card.js:868)
    at HTMLElement.value (chunk.b78314dc93f493d4fbaf.js:10215)
    at HTMLElement.value (chunk.b78314dc93f493d4fbaf.js:10215)
    at HTMLElement.<anonymous> (chunk.b78314dc93f493d4fbaf.js:10215)
    at n (app.5c62d6a4.js:1)
    at chunk.b78314dc93f493d4fbaf.js:14638
```

**Comment by andriej** [comment]
Same here (@0.116.0)

**Comment by rudders** [comment]
This is a documented breaking change in custom integrations - refer:
https://www.home-assistant.io/blog/2020/10/07/release-116/
https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/

Will need an update to the code so suggest you roll back for now.

**Comment by DavidFW1960** [comment]
> Will need an update to the code so suggest you roll back for now.

Hey Adrian.... I was going to ping you about this... Is this a difficult change? Are you able to help?

**Comment by rudders** [comment]
Probably above my pay grade but I'll have a look when I can.

**Comment by DavidFW1960** [comment]
> Probably above my pay grade but I'll have a look when I can.

Really? With the other stuff you already did for this card I thought it would be simple for you... I have also looked at a few other weathercards that have been changed and have a few ideas but I really have no idea at all what I am doing with this.

**Comment by theOzzieRat** [comment]
Change line 9 to:

`var LitElement = LitElement || Object.getPrototypeOf(customElements.get("hui-masonry-view"));`

**Comment by theOzzieRat** [comment]
Actually I think it needs to be:

`var LitElement = LitElement || Object.getPrototypeOf(customElements.get("hui-masonry-view") || customElements.get('hui-view'));`

so that it doesn't break in pre 0.116

**Comment by DavidFW1960** [comment]
well crap! and thanks. That is working now in 0.116!
I'm just going to check in 0.115.6 and then I'll push a PR.
THANK YOU @theOzzieRat Simon.

**Comment by DavidFW1960** [comment]
OK confirmed working in 0.115.6 and 0.116.0
Pushing 0.79 now.

**Comment by DavidFW1960** [comment]
FWIW, it is explained here kinda
https://developers.home-assistant.io/blog/2020/09/30/customViewChanges
So it wasn't actually anything to do with lazyloading that the blog post was pointing to...

**Comment by rudders** [comment]
Cool. I was about to sit down and have a look. Now I'll just upgrade.
