### ISSUE TITLE
Light showers icon seems to be wrong 

### ISSUE THREAD

**Issue by angyp** [DavidFW1960/bom-weather-card#31]
![image](https://user-images.githubusercontent.com/46613600/96196903-4d3b9f80-0f9c-11eb-8f89-538d632a2553.png)

However 

![image](https://user-images.githubusercontent.com/46613600/96196983-7bb97a80-0f9c-11eb-95f4-1e65271dc2d0.png)

I think it's calling rainy-5.svg when maybe it should be calling rainy-2.svg

**Comment by DavidFW1960** [comment]
Well it's in the eye of the beholder right? light-showers is using the rainy-5.svg icon. That is correct. See line 292 in the js file. You could change all references to rainy-5 to rainy-2 on that line to change the icon if you want to. (If you use HACS, delete the .gz file and then CTRL+R a few times and it will change the icon). I'm not going to change this for everyone unless I get a lot more requests for that...

**Comment by angyp** [comment]
Given the showers icon for Saturday and Sunday has the sun in the background you would think the light shower icon would have the sun in the background also.
![image](https://user-images.githubusercontent.com/46613600/96199336-f71e2a80-0fa2-11eb-9be8-275df0f07868.png)

**Comment by DavidFW1960** [comment]
ok fair points!
I will change light-showers from rainy-5 to rainy-2
I will change showers from rainy-3 to rainy-5
I will change heavy-showers from rainy-7 to rainy-6

so taking the sun out of the showers one (and heavy-showers was using a snow icon lol)

What do you think of those changes?

**Comment by angyp** [comment]
I think anything with showers should have a sun in the background.

So light-showers, showers, heavy-showers should be rainy-2, rainy-1, rainy -3 respectively 

I guess it depends on the other states. I assume they also have light-rain, rain, heavy rain. If so they should be rainy-4, rainy-5, rainy-6 respectively

**Comment by DavidFW1960** [comment]
yeah ok... seems ok.
