### ISSUE TITLE
Missing sensor.today_temp_bom after 0.117 upgrade and conversion to bremor BOM collector

### ISSUE THREAD

**Issue by sladey** [DavidFW1960/bom-weather-card#35]
I used the card from your lovelace.yaml and the sensors from template.md.   Most things are working nicely except the max and min temp for the day.  These seem to come from the following sensors which in turn use a state attr of a sensor I cannot find.

`bom_today_max:
        value_template: >
          {{ state_attr('sensor.today_temp_bom', 'max_value') }}`

`bom_today_min:
        value_template: >
          {{ state_attr('sensor.today_temp_bom', 'min_value') }}`

**Comment by DavidFW1960** [comment]
did you add either the statistics or average platform which creates the sensor.today_temp_bom sensor?

**Comment by DavidFW1960** [comment]
Ugh... Look this is probably my fault as the templates.md didn't have the average/statistics in it. It does now. They are in the package file though.

**Comment by sladey** [comment]
hey David, I figured it out too.  I didn't know about the statistics platform and so I learn't something new today !!!  Thanks for all the effort mate with this card.
