### ISSUE TITLE
Unable to create icons folder

### ISSUE THREAD

**Issue by quadhammer** [DavidFW1960/bom-weather-card#37]
https://www.reddit.com/r/homeassistant/comments/drdzye/unable_to_create_icons_folder_in_configwww/

I'm having the same problem as the people In the link above. I can make a folder called 'new folder', but as soon as I try and rename to "icons" it won't let me.  If I try to make the icons folder elsewhere, and then just copy it across, I get "could not find this item".  I'm using the Samba share add-on

**Comment by DavidFW1960** [comment]
The Samba addon hides the icons folder. Change the configuration of samba and delete icons from the exclude list and restart the addon. Then it will work.
