### ISSUE TITLE
Installation in HA .0117+

### ISSUE THREAD

**Issue by leogaggl** [DavidFW1960/bom-weather-card#40]
Could you please shed some light on this comment in the README.md

> "VERY IMPORTANT NOTE: As of HA 0.117.x, the BOM Core Sensor component is removed as it violates ADR14 rule regarding web scraping."

Does this mean it is permanently disabled?

I am trying to install for the first time in this version.

**Comment by DavidFW1960** [comment]
Well yes. Hence the warning. It was removed from HA in 0.117 but fortunately there is a custom component replacement.

**Comment by leogaggl** [comment]
Apologies. I should have read README PROPERLY before opening an issue.

Sometimes it's better to have a break.....

Thank you and keep up the great work!
