### ISSUE TITLE
Feature request: format numbers with selected language

### ISSUE THREAD

**Issue by bieniu** [DavidFW1960/bom-weather-card#41]
Since HA 0.118 the format of numbers is according to the selected language, [PR#7516](https://github.com/home-assistant/frontend/pull/7516).

It would be great if the numbers of the bom-weather-card would be formated the same way.

![image](https://user-images.githubusercontent.com/478555/100079309-c902f480-2e44-11eb-9513-98c0ed1c9111.png)

**Comment by DavidFW1960** [comment]
I don't believe I am controlling that in the card anywhere. What does HA show in dev-tools as the state? Is that formatted correctly? The card should have the same format as the state does.

**Comment by DavidFW1960** [comment]
I was thinking about this last night. Its probably html formatting like described here
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
I'm going to see if I can do this.

**Comment by bieniu** [comment]
Entity states use `.` as a decimal separator. Changing to `,` is a matter of formatting. Maybe you could add this as an option?

**Comment by DavidFW1960** [comment]
As per above I'll see if I can utilise the tolocalesrting in js to do this. I think I can read the locale from HA. I will need you to test this for your system when I get it in there. I may just do the visibility first so you can confirm I'm on the right track. It will be next week as I am going away for a few days.....

**Comment by bieniu** [comment]
Thanks for your effort. You can count on me for testing. Unfortunately, I can't help with `js` because I don't know it.

**Comment by DavidFW1960** [comment]
> I can't help with `js` because I don't know it.

me either lol!! But stay tuned..

**Comment by DavidFW1960** [comment]
Can you try pulling the js file from master (in HACS set to master) and test if the visibility shows the correct number format - that is the only one I have tried so far.
Please let me know if this works for you

**Comment by DavidFW1960** [comment]
I'm 100% sure it works if I edit in the locale to the js however not sure if it will pick it up from the browser or if I have to create a variable to parse it to the js. I hopefully won't have to do that!

**Comment by DavidFW1960** [comment]
Docs in wwew seem to say we should be golden..
[quote] If this parameter is not provided, the toLocaleString() method will use the host environment's current locale.[/quote]

**Comment by bieniu** [comment]
It works for `visibility` but not for `humidity`. Both values in states use `.` as decimal separator

![image](https://user-images.githubusercontent.com/478555/100844287-f3bfff00-347b-11eb-99b8-294673c429df.png)

![image](https://user-images.githubusercontent.com/478555/100844554-4e595b00-347c-11eb-9fa3-9769761ad00b.png)
![image](https://user-images.githubusercontent.com/478555/100844612-60d39480-347c-11eb-8ffe-94e7b9972e30.png)

**Comment by DavidFW1960** [comment]
Yeah like I said I was only trying to prove I worked it out and only did it for visibility! (After 30-60 seconds it will revert too) Now I know I worked it out I will roll it out for humidity etc as well. Stay tuned..

**Comment by bieniu** [comment]
OK, so we have proof that your method works 👍

**Comment by DavidFW1960** [comment]
ok I did visibility, humidity, pressure, temperature (in case you display decimals)
Please confirm it's working for you. The 30 second refresh is also resolved now (I hope) too...
Let me know and I'll draft a new release.....

**Comment by bieniu** [comment]
Everything seems to be working well 👍

![image](https://user-images.githubusercontent.com/478555/100977342-2122b080-3541-11eb-9db9-8cac97054ea2.png)

Thanks for your great work.

**Comment by DavidFW1960** [comment]
Excellent. My pressure has a comma in it now... I wonder why yours doesn't?

**Comment by bieniu** [comment]
Because the state has no decimal numbers

![image](https://user-images.githubusercontent.com/478555/100984021-6bf4f600-354a-11eb-8cd9-2045645ae99d.png)

**Comment by bieniu** [comment]
No, the reason has to be different, I used an entity with decimal numbers and the card shows a rounded value

![image](https://user-images.githubusercontent.com/478555/100984958-aa3ee500-354b-11eb-8bbd-1fb77f76ce47.png)

![image](https://user-images.githubusercontent.com/478555/100985089-d5293900-354b-11eb-9e78-c1034f2cff7d.png)

**Comment by DavidFW1960** [comment]
Interesting. My attributes are same as yours and mine is rounded to zero decimals as well but I get a comma as the thousands separator. Has to be something locale related.. I don't see why else it would do it. Is it convention there to only show a thousands sep if there is more than one digit before? (So >9999)? I dunno....

**Comment by bieniu** [comment]
I added `show_decimals: true` to the card configuration and pressure still hasn't decimals numbers 😊

![image](https://user-images.githubusercontent.com/478555/100986407-7238a180-354d-11eb-8635-5c17660b2a02.png)

**Comment by DavidFW1960** [comment]
Ok I wonder if it's a cache issue... In chrome can you open dev-tools (F12) and right click refresh and select Empty Cache and Hard Reload? Although I get the humidity changed ..... grasping straws..

**Comment by DavidFW1960** [comment]
Also.... thanks for proving I made it work for Temperature as well..

**Comment by bieniu** [comment]
I always reload the page without the cache when changing the card via SHIFT+F5 (Opera), via CTRL+R from dev tools effect is the same.

**Comment by bieniu** [comment]
Precip intensity stil uses `.` as decimal separator.
```entity_pop_intensity: sensor.dom_precipitation```

![image](https://user-images.githubusercontent.com/478555/100989600-4d462d80-3551-11eb-94f0-c33d824cd8c9.png)

![image](https://user-images.githubusercontent.com/478555/100989315-07896500-3551-11eb-8470-3b4417b54065.png)

**Comment by DavidFW1960** [comment]
ok I fixed intensity. Published 0.85a as a pre release. Please test and let me know.

**Comment by DavidFW1960** [comment]
also can you give me your language/locality code so I can see if I can see whats up with the pressure. (mine is en-AU so it's language-region). With chrome the only way to do a full clear cache and hard reload is using the method I describe - there is no keyboard shortcut. Also maybe can you try chrome or another browser if you have it? I'm just perplexed!

**Comment by bieniu** [comment]
> also can you give me your language/locality code

pl-PL


> With chrome the only way to do a full clear cache and hard reload is using the method I describe

I'm using Opera 72 on Windows/Debian/Android. I also tested on Edge.

With 0.85a pop intensity uses `,` as decimal separator but only for 30-40 seconds and than `.` comes back. The same behavior regardless of the browser used.

**Comment by DavidFW1960** [comment]
Hmm... I downloaded Opera and it was fine. I'll take a look at the refresh behaviour tomorrow morning. Odd.

**Comment by DavidFW1960** [comment]
Can you try 0.85b to fix refresh and let me know please?

**Comment by DavidFW1960** [comment]
And I didn't update to 0.85b in the console so it will still say a instead of b. Grrrrrr

**Comment by bieniu** [comment]
Refresh is fixed, I have `,` all the time.

**Comment by DavidFW1960** [comment]
Well that's good! I'm going to check if I missed anything else tomorrow and I'll make a new release. Will also hard-code for your locale and see what I sss in my browser as I don't understand why that is not giving the expected result.

**Comment by bieniu** [comment]
I think now we have the expected result. Each number is displayed in the same way as on the HA core cards. Great work 👍

**Comment by DavidFW1960** [comment]
Except for pressure I assume....

**Comment by bieniu** [comment]
It seems that the thousands separator is not used for pl-PL

![image](https://user-images.githubusercontent.com/478555/101144260-56e69880-3618-11eb-8a08-b15736adddd8.png)

![image](https://user-images.githubusercontent.com/478555/101143826-c019dc00-3617-11eb-9388-eaef3f44e3fe.png)

And here we have value rounding https://github.com/DavidFW1960/bom-weather-card/blob/master/bom-weather-card.js#L441

IMO, everything is fine now, at least for pl-PL.

**Comment by DavidFW1960** [comment]
I'm going to hard code pl-PL today and see what it does here...

**Comment by DavidFW1960** [comment]
You can keep your weather too BTW lol

**Comment by DavidFW1960** [comment]
Can confirm the pl-PL doesn't show the thousands separator as you said so I agree all is well with this now. I don't think I missed anything else and I just bumped to version 0.85c and released.
Thanks for the suggestion and assistance in debugging.
