### ISSUE TITLE
BOM Weather Card - entity_pop

### ISSUE THREAD

**Issue by jcarragher** [DavidFW1960/bom-weather-card#43]
Thanks for you great work.

I started with a fresh HASSIO install and restored just the configuration from a Snapshot. The rest I installed via the Store and HACS.

The BOM Weather Card didn't show anything. I isolated the problem to the entity_pop line. Without this line the weather is displayed.

Lines 935 and 936 of the bom_weather_card.js seems to where there is a problem. On another HA machine I don't have the second line and the weather card is working fine.

      if (this.config.entity_pop && !this.config.alt_pop) try { root.getElementById("pop-text").textContent = `${Math.round(this._hass.states[this.config.entity_pop].state)}` } catch(e) {}
      if (this.config.entity_pop && !this.config.alt_pop) try { root.getElementById("pop-text-today").textContent = `${this._hass.states[this.config.entity_possible_today].state}` } catch(e) {}

**Comment by DavidFW1960** [comment]
are you parsing through entity_possible_today and do you have one of the slots configured to show popforecast?
Can you show your lovelace config for the card please?

**Comment by kineticscreen** [comment]
I'm having a similar issue, having reinstalled this card and the new BOM component after having abandoned it for a while.

Just adding the most basic version shows a bunch of missing elements:
![image](https://user-images.githubusercontent.com/39250334/102435047-10f2f100-406a-11eb-8b4c-7ee0727a42ff.png)

`type: 'custom:bom-weather-card'
title: BOM Weather
entity_current_conditions: sensor.melbourne_icon_descriptor_0
entity_temperature: sensor.melbourne_temp
entity_forecast_high_temp_1: sensor.melbourne_temp_max_1
entity_forecast_high_temp_2: sensor.melbourne_temp_max_2
entity_forecast_high_temp_3: sensor.melbourne_temp_max_3
entity_forecast_high_temp_4: sensor.melbourne_temp_max_4
entity_forecast_high_temp_5: sensor.melbourne_temp_max_5
entity_forecast_icon_1: sensor.melbourne_icon_descriptor_1
entity_forecast_icon_2: sensor.melbourne_icon_descriptor_2
entity_forecast_icon_3: sensor.melbourne_icon_descriptor_3
entity_forecast_icon_4: sensor.melbourne_icon_descriptor_4
entity_forecast_icon_5: sensor.melbourne_icon_descriptor_5
entity_forecast_low_temp_1: sensor.melbourne_temp_min_1
entity_forecast_low_temp_2: sensor.melbourne_temp_min_2
entity_forecast_low_temp_3: sensor.melbourne_temp_min_3
entity_forecast_low_temp_4: sensor.melbourne_temp_min_4
entity_forecast_low_temp_5: sensor.melbourne_temp_min_5
entity_summary_1: sensor.melbourne_short_text_1
entity_summary_2: sensor.melbourne_short_text_2
entity_summary_3: sensor.melbourne_short_text_3
entity_summary_4: sensor.melbourne_short_text_4
entity_summary_5: sensor.melbourne_short_text_5
entity_sun: sun.sun
`

**Comment by DavidFW1960** [comment]
My guess is you don't have all the latest icons.. please unzip the icons file again as the new integration changed some of the conditions and hence new icons were needed.
Can you check your non-working config for the card and make sure every entity you are mapping exists in dev-tools. When the card disappears it means you are parsing a non existent entity through. (ALWAYS means that)

**Comment by kineticscreen** [comment]
Is adding the icons also required when adding via HACS?

**Comment by kineticscreen** [comment]
OK found the problem - the 'standard setup' listed on the repository hasn't been updated with the new sensor names:
wind and gust speeds (you have to have _kilometre or _knots at the end)
It's also now called ..._temp_feels_like (not temperature_feels_like)
Would be really good to build some kind of simple "generator" to automatically create the yaml once provided with the generic sensor / forecast names.

**Comment by DavidFW1960** [comment]
> wind and gust speeds (you have to have _kilometre or _knots at the end)
> It's also now called ..._temp_feels_like (not temperature_feels_like)

Thanks for that correction. I edited the doc. The lovelace.yaml file was right... just the doc still had old sensor name.
Yes you need to manually install the icons.

> Would be really good to build some kind of simple "generator" to automatically create the yaml once provided with the generic sensor / forecast names.

It would be.... I might look at a bash script to create that.

**Comment by DavidFW1960** [comment]
I think I fixed the error for the OP in 0.86b pre-release. Please install that and check

> Lines 935 and 936 of the bom_weather_card.js seems to where there is a problem. On another HA machine I don't have the second line and the weather card is working fine.

**Comment by DavidFW1960** [comment]
closing as I believe it's fixed and the OP isn't commenting
