### ISSUE TITLE
Card Width Issue Using Companion App

### ISSUE THREAD

**Issue by stmrocket** [DavidFW1960/bom-weather-card#45]
I migrated to your wonderful card as part of moving from Darksky to OpenWeatherMap.  On desktop, it works perfectly, however, in the Android companion app, the card causes the page to become wider than the screen as shown in the images below (the page scrolls side to side instead of having chevrons on the top bar).  I have tried both with my layout tweaks and with the default configuration and it makes no difference.  Removing the card returns the page width to normal.  I have skimmed the code looking for a culprit but I am no expert...

![screenshot1](https://user-images.githubusercontent.com/19308297/105117264-d548ae00-5a91-11eb-998b-02399048cf2f.jpg)
![screenshot2](https://user-images.githubusercontent.com/19308297/105117266-d548ae00-5a91-11eb-8cf2-4642bdf811dc.jpg)

**Comment by DavidFW1960** [comment]
no idea and I don't have/use android. It doesn't do this in iOS app. Have you tried maybe putting the card in a vertical stack? I use it in a stack. I can't replicate this in any case and seems maybe to be an android app issue....

**Comment by stmrocket** [comment]
No problem!  I do have the card in a vertical stack.  I'll keep an eye on the issues for the app as it does sound like an issue there although I am only seeing it with this card (so far...).

**Comment by DavidFW1960** [comment]
Someone reported a similar issue with the bom radar card but of course you're not in Australia anyway....
Perhaps ask the android guys... they might be able to assist with advice as to what might be causing it..

**Comment by stmrocket** [comment]
Thanks!  I'll keep an eye on the radar card issue even though the card doesn't apply to me and will ask the Android guys for advice.  I just ran through the code again in WinMerge alongside the Darksky card's code and nothing jumps out as the culprit so I believe that is where the issue lies.
