### ISSUE TITLE
sensor.bom_today_max value unkown

### ISSUE THREAD

**Issue by exup** [DavidFW1960/bom-weather-card#46]
Hi I am trying to work out why since the recent upgrade for HASSIO and updated the your integrations and BOM its not finding this value. All other values are ok. So just want to understand how your weather yaml code works for find out why its not collecting it.
I have tried both methods using the average integration as per your guide. It was working prior to upgrade.

I am using warrawee as my custom local connection and Terrey Hills for everything else (as per the setup prompts)
I did unistall the bureau meterology integration and reinstalled it, same for your custom card.

So sensor.bom_today_max = unknown, and sensor.warrawee_temp_max_0 = 25 (I waited 24 hours in case it took time to update)
Below is screen shot of your weather.yaml and snippet of what I have in my card.

entity_daytime_high: sensor.bom_today_max
entity_daytime_low: sensor.bom_today_min

![image](https://user-images.githubusercontent.com/61529003/107863272-0c4e8b80-6ea7-11eb-99c3-8c11195e22e5.png)

![image](https://user-images.githubusercontent.com/61529003/107863337-bdedbc80-6ea7-11eb-99a9-125724d87efd.png)

**Comment by DavidFW1960** [comment]
The bom_today_min and bom_today_max are created from sensor_today_temp_bom which either uses statistics sensor or I prefer to use a custom component average. You can only use one or the other. Then if a sensor goes n/a it should use that sensor instead of reporting n/a and passing that to the card.

Its impossible to tell what you are actually doing as you posted a screenshot os a small section of the code. 

so..
Check that all the sensors actually exist and that none of their states are n/a and check the log for errors.
Post your edited weather.yaml so I can see your error.

**Comment by exup** [comment]
Hi, all the sensor entities (115 in total) have values, only some future forecast events are unknown, but I assume that is ok. For example sensor.warrawee_uv_category_4 (5 and 6) are unknown or uv_end_time_4 etc.

One exception is from this morning it was showing a value the "**sensor.warrawee_temp_min_0**" has moved to unknown.

The log is showing this error;

> Logger: custom_components.average.sensor
Source: custom_components/average/sensor.py:411
Integration: average (documentation)
First occurred: 10:36:00 AM (490 occurrences)
Last logged: 2:40:45 PM

> Unable to find an entity "sensor.terrey_hills_temperature"

So  I suspect it the issue as it should be "**sensor.terrey_hills_temp**" but I dont think I made that edit? I seems to have created itself or is it left over from the previous vesions of Bureau of Meterology integration?
But as mentioned I removed the Bureau and reinstalled the BOM card. Plus upgraded the "average" integration
 
Here is the weather.yaml in full attached as a txt file.




[weather.txt](https://github.com/DavidFW1960/bom-weather-card/files/5976973/weather.txt)

**Comment by DavidFW1960** [comment]
so you are using average but you are not using the right sensor?
```
# IMPORTANT NOTE IF YOU USE average, you must comment out the below statistics sensor. Both cannot exist
  - platform: average
    name: today_temp_bom
    entities:
      - sensor.terrey_hills_temperature
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
```

I think with the new integration from Brendan the sensor name is sensor.terrey_hills_temp not temperature. So that is for sure an issue.
Check that  sensor.terrey_hills_temp and today_temp_bom exist and you should then be good.

**Comment by exup** [comment]
Hi, 
so I have gone through the weather.yaml and found a few references to sensor.terrey_hills_temperature so edited them to just be **sensor.terrey_hills_temp** (see attached)

I am getting a valid value for **sensor.terrey_hills_temp** of 20.5
and **sensor.today_temp_bom** = 18.5
But still it displays unknown for in the card Max and Min. The card is using the value **sensor.bom_today_max**

**entity_daytime_high: sensor.bom_today_max
entity_daytime_low: sensor.bom_today_min**


I am trying to work out how the sensor.bom_today_max/min is calculated from.  Looking at the weather.yaml code its seems to be calculated from the code section below, if I read it right, if **sensor.warrawee_max_0** is N/A use **sensor.today_temp_bom max** value? Else if it does have a value (which it does) use that instead?

>       bom_today_max:
>        value_template: >
>          {%- if states('sensor.warrawee_max_0') == 'n/a' -%} 
>            {{ state_attr('sensor.today_temp_bom', 'max_value') }}
>          {% else %}
>            {{ states('sensor.warrawee_max_0') }}
>          {% endif %}

I see this too is wrong, it should be sensor.warrawee_**temp**_max_0.  I changed it and it works for MAX
but for min the sensor.warrawee_temp_min_0 is getting a value of "**unknown**" not "**n/a**" 
So I also changed this as well and now it all works.

As I uninstalled the Bureau of Metrology integration and installed it, should it have correctly setup the yaml file without these mistakes or its still up to me to go through and manually change all this. Should I open a ticket with Brendan git hub page as its not related to your card?

[weather.txt](https://github.com/DavidFW1960/bom-weather-card/files/5979554/weather.txt)

**Comment by DavidFW1960** [comment]
It's not really an issue as such. Brendans integration ended up with different sensor names but that's mostly because the BOM source he uses had different names. Compatibility with old names wasn't even a consideration. I did go through the instructions for the card updating them for the new names. I know it's a PITA but hopefully a one-off now you have the card working.

The card actually oesn't care what sensors you use or pass through. Plenty of people outside Australia use it with their weather providers as the card doesn't know or care as long as you provide the required data it will work anywhere.

Glad you got it going.

**Comment by exup** [comment]
Yes I will close this, thanks for acting as a sound board for this problem solving exercise. I learnt alot about how it all works and can see you can tune it a bit.
