### ISSUE TITLE
Icons are not rendered if base URL contains "night"

### ISSUE THREAD

**Issue by xBelladonna** [DavidFW1960/bom-weather-card#47]
Hello! I updated to the latest 0.87b and started having issues with the forecast icons not rendering. I've narrowed down the problem to the way the Home Assistant URL has `.replace("night", "day")` called on it, which presents a problem if the base URL contains the sequence "night" in it, like mine does, causing the images to be retrieved from an invalid URL. I'm unfamiliar with this codebase so I'm unsure of the best way to solve this problem, but I'd suppose performing the replace on more specific parts of the URL where required, leaving the base URL unmodified would work?

**Comment by DavidFW1960** [comment]
Hmm.... why ever do you do that??
I changed .replace("night", "day" to .replace("-night", "-day")
This is in pre-release of 0.88b - does that correct this?

**Comment by xBelladonna** [comment]
Well, I do that because Nightshade is my last name, and I figured I could use my name for my website where I host HA, nightshade.fun. The latest preview does work but will break for anyone with `-night` in their URL, though I suppose that problem can be addressed if/when it's encountered. Thanks very much for the fix!

**Comment by DavidFW1960** [comment]
Yeah.... what are the odds someone will have night with a hyphen though...... I have a couple more complicated fixes if I come across that. Glad it's fixed for you now though
