### ISSUE TITLE
Idea - create entity tap actions

### ISSUE THREAD

**Issue by kineticscreen** [DavidFW1960/bom-weather-card#48]
Would be great to be able to tap each item, and bring up the sensor's standard more-info box. (ie, tapping on the tempearture brings up the sensor.bom_xx_ sensor, for viewing its history, etc.

Would also love it if the forecast panels were expandable / collapsed by default.

**Comment by DavidFW1960** [comment]
First isn't possible so far as I know and/or outside my capabilities
Same for second actually.
Sorry I didn't see this before now.
