### ISSUE TITLE
Feature request: option to use old icons

### ISSUE THREAD

**Issue by bieniu** [DavidFW1960/bom-weather-card#5]
In my opinion, the new icons look much worse than the old ones.
I think the best solution would be to choose icons in the card configuration.
Is it possible?

**Comment by andriej** [comment]
I have the same feeling, UI lost it's WAF after the update...

**Comment by DavidFW1960** [comment]
hmm...
So even the latest updated ones?
It's actually easy enough for you to fix this. I will post how to do this in a bit when I work it out....

**Comment by DavidFW1960** [comment]
OK I added the old icons in weather_icons_OLD.zip so download that and overwrite your icons.

NOTE: Make sure you clear cache/refresh a couple of times.....
Also I DID make all the icons smaller yesterday so if it's size that's the issue, maybe you need to refresh?
Anyway, please report back.....

**Comment by bieniu** [comment]
With icons from the file weather_icons_OLD.zip card looks amazing again! Thanks.

**Comment by DavidFW1960** [comment]
'M going to re-open this. I am going to make a configuration option to use either old or new icons. It's not too hard and maybe worthwhile.

**Comment by DavidFW1960** [comment]
OK I just pushed an update. Will be in HACS soon.
Revert to the old icons zip file.
If you add:
```
old_icon: true
```
to lovelace for the card it will render the old icons. ANY value for that key, true false, anything will render the old ones. So you need to comment that out to use the new icons.
