### ISSUE TITLE
Home Assistant reports invalid repository URL.

### ISSUE THREAD

**Issue by mekatrol** [DavidFW1960/bom-weather-card#50]
### **Home Assistant Version:** 
Version
core-2021.4.5
[latest]

### **Repro steps:**

1. Navigate to 'Supervisor | Add-on Store'
2. Top right drop down menu (3 dots) | Repositories
3. Enter URL 'https://github.com/DavidFW1960/bom-weather-card' and click Add
4. Check system logs to see errors below

### **Error log:**
21-04-17 06:31:46 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/DavidFW1960/bom-weather-card repository
#### 21-04-17 06:31:48 **ERROR (MainThread) [supervisor.store] https://github.com/DavidFW1960/bom-weather-card is not a valid add-on repository**
21-04-17 06:31:48 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 8ee35b6c
21-04-17 06:31:48 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 8ee35b6c
21-04-17 06:31:48 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/8ee35b6c
21-04-17 06:31:48 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
21-04-17 06:31:48 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 8ee35b6c
21-04-17 06:31:48 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/DavidFW1960/bom-weather-card

**Comment by DavidFW1960** [comment]
This is a card not a custom_component or an addon. Only addons are installed via supervisor.

This repo is a HACS default Lovelace/Frontend repo and can be installed from HACS as such.. no need to add as a repo.

It can also be manually installed by following the instructions.
