### ISSUE TITLE
Unable to create www/icons folder in HA

### ISSUE THREAD

**Issue by austwhite** [DavidFW1960/bom-weather-card#51]
This is not an issue with this card as such, but due to this issue I am unable to install the card correctly.
Using the current (2021.4.x) version of Home Assistant, trying to create the folder config\www\icons fails.
I can create a folder of any other name, but trying to create this folder does not work.
When I go to a TTY terminal and create the folder manually on Home Assistant, the folder can create but is not visible via a share.

I am using Home Assistant, with Home Assistant OS (HassOS).

Any advice would be helpful with this.

**Comment by austwhite** [comment]
Found the solution.  Will close this.  For some unknown reason the default setting of SAMBA addon vetos icon? folders

**Comment by DavidFW1960** [comment]
Yep. Just remove icons from vetos. I have no idea why the samba addon does this.
