### ISSUE TITLE
Wind Speed throwing an error

### ISSUE THREAD

**Issue by CAL20** [DavidFW1960/bom-weather-card#57]
Hi,

When I enter the following line into the card, the card displays nothing:
"entity_wind_speed: sensor.sydney_observatory_hill_wind_speed_kilometer"

With this line removed, everything else seems to be working, looking like your example card.  Animations, etc all work (It is great card and love the way it looks!!!).  I seem to have the entity imported from the BOM integration and it seems to graph with reasonable values.

I think I have copied over all of your icons, directories, weather.yaml, etc.  (I am still new to HA, so wasn't sure where resources... type:module text should go)

It all otherwise looks ok, and thanks for your help.

Craig

**Comment by DavidFW1960** [comment]
If you installed via HACS it will have added the resource for you. The fact the card loads at all means you heve this defined correctly. It's under configuration>lovelace>resources tab...

If the card doesn't display it means you are parsing an entity that doesn't exist, in this case does sensor.sydney_observatory_hill_wind_speed_kilometer exist if you check in dev-tools? When you configured the BOM sensors (Brendans component) did you turn on all options for the observation and forecast sensors? It may be that that weather station doesn't publist wind speed to.... but if it doesn't exist and you are parsing it to the card then the card won't display.

**Comment by CAL20** [comment]
Apologies for wasting your time.
I thought I had looked last night in the dev-tools and it appeared to have values.  I tried again this morning and there was nothing.  I tried to graph it, and it failed.  I refreshed and now it graphs and works in your excellent card.
Thanks very much for all the excellent work, it is a great looking card and my wife only likes BOM!!
Thanks

**Comment by DavidFW1960** [comment]
How odd... Glad it's working.
