### ISSUE TITLE
weather_icons.zip is missing the amcharts additions icons

### ISSUE THREAD

**Issue by Joakler** [DavidFW1960/bom-weather-card#6]
First off, Thanks. Nice work here. It looks amazing. Took me a while to get it working fully.

Issues I had was that an icon for entity_current_conditions would not display for a current state of 'storm'. I poked through the js and found it was looking for scattered thunderstorms icon which was missing from the weather_icons.zip. Found the icons on SouthernWolf95 additions and added them to the icons directory. This still didn't work until I had renamed the files to remove the uppercase and -Animated/-Static parts of the file name. For example -> 'Scattered-Thunderstorms - Animated.svg' changed to 'scattered-thunderstorms.svg. So really the issue is just the zip doesn't contain all the files which makes the install instructions a bit confusing.

**Comment by DavidFW1960** [comment]
Which provider are you using that has 'storm' as a condition?
Can you give me a list of all conditions for that provider and I will add them to the js file and use appropriate icons.

Sorry - for some reason I don't get notifications for this repo. Very strange! So I only just saw this issue.

**Comment by DavidFW1960** [comment]
Further to this, the js file does have storm as a condition and there is an icon for it - scattered-thunderstorms....
Are you using the latest version of the card? Did you download the latest icons file?
