### ISSUE TITLE
Icons are not loading

### ISSUE THREAD

**Issue by eaglefox82** [DavidFW1960/bom-weather-card#61]
Hi,
I have installed your Card via HACS.
While everything looks great, I can not getting the icons to load

using the following:
entity_current_conditions: sensor.richmond_icon_descriptor_0, HA provides a value of mostly_sunny

![image](https://user-images.githubusercontent.com/20160019/131348225-40f308b7-3310-472f-b214-316b3db25e4c.png)

Is there something I am missing?

![image](https://user-images.githubusercontent.com/20160019/131347838-fed5fad1-9aab-4f29-ad36-68b7b94e49c1.png)

Also, how do we get a background like the one in your images.
Thanks

This is the whole code for my card

type: custom:bom-weather-card
title: BOM Weather
entity_current_conditions: sensor.richmond_icon_descriptor_0
entity_temperature: sensor.richmond_temp
entity_wind_bearing: sensor.richmond_wind_direction
entity_forecast_high_temp_1: sensor.richmond_temp_max_1
entity_forecast_high_temp_2: sensor.richmond_temp_max_2
entity_forecast_high_temp_3: sensor.richmond_temp_max_3
entity_forecast_high_temp_4: sensor.richmond_temp_max_4
entity_forecast_high_temp_5: sensor.richmond_temp_max_5
entity_forecast_icon_1: sensor.richmond_icon_descriptor_1
entity_forecast_icon_2: sensor.richmond_icon_descriptor_2
entity_forecast_icon_3: sensor.richmond_icon_descriptor_3
entity_forecast_icon_4: sensor.richmond_icon_descriptor_4
entity_forecast_icon_5: sensor.richmond_icon_descriptor_5
entity_forecast_low_temp_1: sensor.richmond_temp_min_1
entity_forecast_low_temp_2: sensor.richmond_temp_min_2
entity_forecast_low_temp_3: sensor.richmond_temp_min_3
entity_forecast_low_temp_4: sensor.richmond_temp_min_4
entity_forecast_low_temp_5: sensor.richmond_temp_min_5
entity_summary_1: sensor.richmond_short_text_1
entity_summary_2: sensor.richmond_short_text_2
entity_summary_3: sensor.richmond_short_text_3
entity_summary_4: sensor.richmond_short_text_4
entity_summary_5: sensor.richmond_short_text_5
entity_sun: sun.sun
entity_daytime_high: sensor.richmond_temp_max_0
entity_daytime_low: sensor.richmond_temp_min_0
entity_wind_speed: sensor.richmond_wind_speed_kilometre
entity_wind_gust: sensor.richmond_gust_speed_kilometre
entity_humidity: sensor.richmond_humidity
entity_apparent_temp: sensor.richmond_temp_feels_like
entity_daily_summary: sensor.richmond_extended_text_0
entity_pop: sensor.richmond_rain_chance_0
entity_pop_intensity: sensor.richmond_rain_since_9am
entity_possible_today: sensor.richmond_rain_amount_range_0
entity_pos_1: sensor.richmond_rain_amount_range_1
entity_pos_2: sensor.richmond_rain_amount_range_2
entity_pos_3: sensor.richmond_rain_amount_range_3
entity_pos_4: sensor.richmond_rain_amount_range_4
entity_pos_5: sensor.richmond_rain_amount_range_5
entity_pop_1: sensor.richmond_rain_chance_1
entity_pop_2: sensor.richmond_rain_chance_2
entity_pop_3: sensor.richmond_rain_chance_3
entity_pop_4: sensor.richmond_rain_chance_4
entity_pop_5: sensor.richmond_rain_chance_5
entity_uv_alert_summary: sensor.richmond_uv_category_0
locale: en
static_icons: false
tooltip_bg_color: rgb( 75,155,239)
tooltip_border_color: orange
tooltip_border_width: 3
tooltip_caret_size: 10
tooltip_fg_color: '#fff'
tooltip_left_offset: -12
tooltip_width: 100
tooltips: true
old_daily_format: false
time_format: 12
show_beaufort: true
old_icon: 'true'
show_decimals: false

**Comment by DavidFW1960** [comment]
where did you install the icons to?

**Comment by eaglefox82** [comment]
Sorry I missed the icon upload part, all is working now. Thanks
