### ISSUE TITLE
Weather Card Icons not found

### ISSUE THREAD

**Issue by JacobBakker** [DavidFW1960/bom-weather-card#64]
![image](https://user-images.githubusercontent.com/92369812/137706378-2e9a6841-e098-4e46-b382-845343d0d4b6.png)

Double checked paths files etc. In the console I can see that the the Card cannot find the relevant animated picture.  

When I use File Explorer in Chrome, access the animated picture via Samba, open it and it shows up with following in the address line:

file://10.1.1.100/config/www/Icons/weather_icons/animated/fair-day.svg.

It is probably a very simple solution but I break my head about it. Advise is appreciated.

**Comment by DavidFW1960** [comment]
It appears you have not downloaded and unzipped the icons file as per the instructions..
