### ISSUE TITLE
Request/help: Right side column with left aligned text and icons

### ISSUE THREAD

**Issue by grastraa** [DavidFW1960/bom-weather-card#67]
Would it be possible to change the alignment of the right hand side here:
![image](https://user-images.githubusercontent.com/67679349/147366649-daab59c7-58a2-4645-a0ca-560957df946d.png)
to instead, look something like how this card displays information:
![image](https://user-images.githubusercontent.com/67679349/147366698-821ae675-6585-4017-9337-fee7b643672e.png)
Text alignment to the right, and icons displayed 'after'. 

It'd really help with aesthetics, especially in regards to how much wind gust blows everything toward the centre.

Happy to have to tinker myself, I'm just a bit clueless about how to approach it.

**Comment by DavidFW1960** [comment]
what will happen now is that it will move everything to 1 column. it's also left justifying the column. I think aesthetically I prefer this to your suggested behavior.

**Comment by grastraa** [comment]
Would you be able to point me toward the code that I should tinker with so I could obtain my goal? I would be very thankful.

**Comment by DavidFW1960** [comment]
lines 43-91. Good luck

**Comment by DavidFW1960** [comment]
Latest commit aligns the right column to centre. If you pull the master cods and try. I will release as beta tomorrow
