### ISSUE TITLE
template issue

### ISSUE THREAD

**Issue by jonwaland** [DavidFW1960/bom-weather-card#68]
`2021-12-29 07:27:59 WARNING (MainThread) [homeassistant.helpers.template] Template warning: 'round' got invalid input 'unknown' when rendering template '{{states('sensor.pymble_temp_max_6')|round(0)}}°/{{states('sensor.pymble_temp_min_6')|round(0)}}°/{{states('sensor.pymble_rain_chance_6')|round(0)}}%' but no default was specified. Currently 'round' will return 'unknown', however this template will fail to render in Home Assistant core 2022.1`

Presumably there was no day 6th forecast. My code is as per yours on here, with no defaults on the round.

**Comment by DavidFW1960** [comment]
so this is the mini card right? I handle this in Lovelace by a conditional card like this:
```
         - type: entities
            title: BOM Forecast
            show_header_toggle: false
            entities:
              - sensor.bom_forecast_0
              - sensor.bom_forecast_1
              - sensor.bom_forecast_2
              - sensor.bom_forecast_3
              - sensor.bom_forecast_4
              - sensor.bom_forecast_5
              - type: 'custom:hui-element'
                card_type: conditional
                conditions:
                  - entity: sensor.bom_forecast_6
                    state_not: "unknown°/unknown°/unknown%"
                card:
                  type: entities
                  card_mod:
                    style: |
                      ha-card {
                        box-shadow: none;
                        --ha-card-background: rgba(0, 0, 0, 0);
                        margin: -16px -16px -16px -16px;
                      }
                  entities:
                  - entity: sensor.bom_forecast_6
```
There is a default set for the round in that template anyway and I haven't seen that error.
You could try this:
```
      bom_forecast_6:
        friendly_name_template: >
          {%- set date = as_timestamp(now(),default='n/a') + (6 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)',default='n/a') }}
        value_template: >
          {%- if states('sensor.kariong_temp_max_6') == 'unknown' -%} 
            {{ states('sensor.kariong_temp_max_6')|round(0)}}°/{{states('sensor.kariong_temp_min_6')|round(0)}}°/{{states('sensor.kariong_rain_chance_6')|round(0) %}}
          {% else %}
            {{"unknown°/unknown°/unknown%"}}
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.kariong_icon_descriptor_6') ~ '.png' }}
```
which should fix the error but it hasn't bothered me although possibly not looking for it either. If that works for yu let me know and I can edit the suggested template in the docs.

**Comment by jonwaland** [comment]
nope - this is from my weather package (based on yours) feeding you bom-weather-card.

Shouldn't the code be more like:

```
        value_template: >
          {%- if states('sensor.pymble_temp_max_6') != 'unknown' -%}
            {{states('sensor.pymble_temp_max_6')|round(0,default='none')}}°/{{states('sensor.pymble_temp_min_6')|round(0,default='none')}}°/{{states('sensor.pymble_rain_chance_6')|round(0,default='none')}}%
          {% else %}
            {{"unknown°/unknown°/unknown%"}}
          {% endif %}
```

(with an endif and != rather than == )

**Comment by DavidFW1960** [comment]
Yes you're right. or you can switch the returned template. either will work.
round(0) sets the default to 0 so you don't need default='none' that works in all my other ones..

**Comment by jonwaland** [comment]
well, I've done the change I posted - not seeing any issues; but excluding the ones on the 29th, I'd not seen them before anyway...

**Comment by DavidFW1960** [comment]
all good Jon. thanks

**Comment by DavidFW1960** [comment]
Jon, I just updated the template by setting default='unknown' I saw that error today and this fixes it along with a custom card in Lovelace as I showed you earlier.

**Comment by jonwaland** [comment]
interesting that you got it now. ok - will take a look

**Comment by DavidFW1960** [comment]
IT is just variable. Happens variably (which is why I did the lovelace conditional card) like max and min obs disappear during the day as well.
