### ISSUE TITLE
Visibility missing when converting from Dark Sky card

### ISSUE THREAD

**Issue by BradleyFord** [DavidFW1960/bom-weather-card#7]
I just converted over from the original Dark Sky card, everything seems to be working perfectly except the Visibility is no longer shown in the UI.

Any thoughts?

**Comment by DavidFW1960** [comment]
Are you parsing the visibility through to a slot position? I did change the defaults some time ago and visibility will need to be specified to display

Also sorry - I only just saw this. I don't understand why I don't get notifications..

**Comment by BradleyFord** [comment]
Hi David,

I am not actually specifying a position, just directly passing it to the "entity_visibility", assuming it would be the same as the previous configuration.
Do we now need to be more specific?


It is located near the bottom
```
entity_apparent_temp: sensor.dark_sky_apparent_temperature
entity_current_conditions: sensor.dark_sky_icon
entity_daily_summary: sensor.dark_sky_daily_summary
entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
entity_forecast_icon_1: sensor.dark_sky_icon_1d
entity_forecast_icon_2: sensor.dark_sky_icon_2d
entity_forecast_icon_3: sensor.dark_sky_icon_3d
entity_forecast_icon_4: sensor.dark_sky_icon_4d
entity_forecast_icon_5: sensor.dark_sky_icon_5d
entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0d
entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1d
entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2d
entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3d
entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4d
entity_humidity: sensor.dark_sky_humidity
entity_pop: sensor.dark_sky_precip_probability
entity_pop_1: sensor.dark_sky_precip_probability_1d
entity_pop_2: sensor.dark_sky_precip_probability_2d
entity_pop_3: sensor.dark_sky_precip_probability_3d
entity_pop_4: sensor.dark_sky_precip_probability_4d
entity_pop_5: sensor.dark_sky_precip_probability_5d
entity_summary_1: sensor.dark_sky_summary_1d
entity_summary_2: sensor.dark_sky_summary_2d
entity_summary_3: sensor.dark_sky_summary_3d
entity_summary_4: sensor.dark_sky_summary_4d
entity_summary_5: sensor.dark_sky_summary_5d
entity_sun: sun.sun
entity_temperature: sensor.dark_sky_temperature
entity_visibility: sensor.dark_sky_visibility
entity_wind_bearing: sensor.dark_sky_wind_bearing
entity_wind_speed: sensor.dark_sky_wind_speed
tooltip_border_width: 0
tooltips: true
type: 'custom:bom-weather-card'
```

**Comment by DavidFW1960** [comment]
Yes but the card is not displaying that entity by default anymore. There are 5 Left and 5 Right slots. The card used to automatically map the visibility to one of those slots however I changed the defaults a FW releases back... so now if you want to see the visibility to have to add that to the card config. This is in the docs..

```
Slots

The current condition columns are specified by 'slots'. There are 5 left column slots (designated l1 - l5) and 5 right column slots (designated r1 - r5). There are currently 10 possible values that can be assigned to a slot. These are:

daytime_high
daytime_low
wind
visibility
sun_next (the next sun event ... sunset or sunrise)
sun_following (The following sun event ... if sun_next is a sunset then this will be the following sunrise and vice versa)
pop (probability of precipitation)
humidity
pressure
uv_summary
fire_summary
possible_today (possible rainfall today)
possible_tomorrow (possible rainfall tomorrow)
empty (empty slot... the slot below does not rise to fill the space)
remove (same as empty but the slot below rises to take the place of the slot)
```

**Comment by BradleyFord** [comment]
I have been playing around with it a bit and also looking at your configuration; the slots seem to be about right but they keep dumping in 2 rows for both even though I have only configured 1.
If I try bumping slot_l3 down by adding an "empty" it still has the duplication except they are both pushed down a row.
If I put l3 and l4 both as "Sun_next" then I only get 3 rows of "sun_next" in the output.

![Double sun times](https://user-images.githubusercontent.com/322815/78070358-4ce30a80-73a4-11ea-9a52-2fb9ded8e8df.JPG)

(Good to see a fellow Australian, except I'm living in Moscow.; and thanks for reviving this old code)

**Comment by BradleyFord** [comment]
Ah ok, that is clear if I switch from default to slots I need to fill all
slots even if the empty ones are "remove".

Thank you so much for the help.
