### ISSUE TITLE
Weather Card Config - weather.yaml question

### ISSUE THREAD

**Issue by jkelly73** [DavidFW1960/bom-weather-card#71]
Hi David,
I have had to reconfigure my HA and weather card and have 1 remaining issue that I cannot solve.

The large text summary line in the centre of the card that should say "Shower", "Cloudy" etc (immediately below the top icons) will only display "unknown".

I think it is trying to use (in my case) "sensor.murrays_run_icon_descriptor_0".  When I check the value of this entity in Dev tools, it (currently) shows "shower", yet the card shows "Unknown".

Any advice as to how I can fix this one remaining issue?

Thanks
Jon

**Comment by DavidFW1960** [comment]
Which entity have you passed for current conditions text? I normally use a template sensor with the summary/short text for this. See the relevant part of the docs.

**Comment by jkelly73** [comment]
In my card configuration, the current conditions currently reads:

`entity_current_conditions:` sensor.murrays_run_icon_descriptor_0'

When I put sensor.murrays_run_icon_descriptor_0 into the developer tools to check the state (today) it says "shower" and the animated image shows accordingly.

Putting "sensor.murrays_run_short_text_0" into the developer tools returns "unknown".

Looking at the weather.yaml file, it appears to parse bom.current_text, but I dont have this entity - This could be my problem??


I have attached my weather.yaml file as I suspect something isnt quite right (but I have no idea what).

Thanks again for any pointers,
Jon
[weather.txt](https://github.com/DavidFW1960/bom-weather-card/files/7859463/weather.txt)

**Comment by DavidFW1960** [comment]
bom.current_text is created from sensor.murrays_run_short_text_0 via a template sensor. If yours shows unknown it means theres a problem with the BOM integration
![image](https://user-images.githubusercontent.com/36390762/149258218-661c861f-20a4-45bd-b13e-20a3954cf386.png)
you can use sensor.murrays_run_icon_descriptor_0 if you want to.

**Comment by jkelly73** [comment]
Thanks David.  Ive removed and reinstalled the BOM card.  It seems to install and be working as it should.  It picks up the correct LAT / Long from my HA config and installs all 107 entities again (I sleected everything).

sensor.murrays_run_icon_descriptor_0 seems to contain the correct information but it does not make its way into your card when I put it into the card config as:
entity_current_conditions: sensor.murrays_run_icon_descriptor_0

bom.current_text remains "unknown" even after a resinstall of the BOM card.

Im not sure whats going on.  I do know that on my old config (different machine) it used to work using the same weather location and entity_current_conditions: sensor.murrays_run_icon_descriptor_0

Any thoughts or suggestions would be greatly appreciated.

Thx
Jon

**Comment by DavidFW1960** [comment]
bom.current_text is a template sensor created from the short text. If the sensor is UNKNOWN then check your template. There is the full template in templates.md as well as in the readme.

**Comment by jkelly73** [comment]
Thanks David,
I was amending the wrong line in the lovelace config.  By replacing sesnor.bom_current_text with sensor.murrays_run_icon_descriptor_0 I now get "shower" instead of "unknown".  So its working. Great.

Id still love to know / understand why sensor.bom_current_text isnt working and reporting "unknown".  I cant for the life of me spot the difference in my templates from the github ones, but I guess there must be somewhere!


Thanks again.
Jon

**Comment by DavidFW1960** [comment]
can you copy the template exactly as you are using it in here so I can take a look?

**Comment by jkelly73** [comment]
Hi David,
Many thanks.  Below as requested, happy to provide more info if required.  This is my lovelace card:
`
type: custom:bom-weather-card
title: BOM Weather
entity_current_conditions: sensor.murrays_run_icon_descriptor_0
entity_temperature: sensor.mangrove_mountain_temp
entity_forecast_high_temp_1: sensor.murrays_run_temp_max_1
entity_forecast_high_temp_2: sensor.murrays_run_temp_max_2
entity_forecast_high_temp_3: sensor.murrays_run_temp_max_3
entity_forecast_high_temp_4: sensor.murrays_run_temp_max_4
entity_forecast_high_temp_5: sensor.murrays_run_temp_max_5
entity_forecast_icon_1: sensor.murrays_run_icon_descriptor_1
entity_forecast_icon_2: sensor.murrays_run_icon_descriptor_2
entity_forecast_icon_3: sensor.murrays_run_icon_descriptor_3
entity_forecast_icon_4: sensor.murrays_run_icon_descriptor_4
entity_forecast_icon_5: sensor.murrays_run_icon_descriptor_5
entity_forecast_low_temp_1: sensor.murrays_run_temp_min_1
entity_forecast_low_temp_2: sensor.murrays_run_temp_min_2
entity_forecast_low_temp_3: sensor.murrays_run_temp_min_3
entity_forecast_low_temp_4: sensor.murrays_run_temp_min_4
entity_forecast_low_temp_5: sensor.murrays_run_temp_min_5
entity_summary_1: sensor.murrays_run_extended_text_1
entity_summary_2: sensor.murrays_run_extended_text_2
entity_summary_3: sensor.murrays_run_extended_text_3
entity_summary_4: sensor.murrays_run_extended_text_4
entity_summary_5: sensor.murrays_run_extended_text_5
entity_sun: sun.sun
entity_daytime_high: sensor.murrays_run_temp_max_0
entity_daytime_low: sensor.murrays_run_temp_min_0
entity_wind_bearing: sensor.mangrove_mountain_wind_direction
entity_wind_speed: sensor.mangrove_mountain_wind_speed_kilometre
entity_wind_gust: sensor.mangrove_mountain_gust_speed_kilometre
entity_humidity: sensor.mangrove_mountain_humidity
entity_apparent_temp: sensor.mangrove_mountain_temp_feels_like
entity_daily_summary: sensor.murrays_run_extended_text_0
entity_pop_intensity: sensor.mangrove_mountain_rain_since_9am
entity_current_text: sensor.murrays_run_icon_descriptor_0
entity_uv_alert: sensor.bom_uv_alert
entity_fire_danger: sensor.bom_fire_danger
entity_fire_danger_summary: sensor.bom_fire_danger
entity_uv_alert_summary: sensor.uv_cat_formatted
locale: en
sunset: true
static_icons: false
old_icon: hybrid
tooltip_bg_color: rgb( 75,155,239)
tooltip_border_color: rgb(255,161,0)
tooltip_border_width: 1
tooltip_caret_size: 5
tooltip_fg_color: '#fff'
tooltip_left_offset: -12
tooltip_width: 110
tooltips: true
old_daily_format: false
time_format: 24
show_beaufort: false
refresh_interval: 60
show_separator: false
temp_top_margin: 0px
temp_font_weight: 300
temp_font_size: 4em
temp_right_pos: 0.85em
temp_uom_top_margin: '-12px'
temp_uom_right_margin: 4px
apparent_top_margin: 45px
apparent_right_pos: 1em
apparent_right_margin: 1em
current_text_top_margin: 4.5em
current_text_left_pos: 0px
current_text_font_size: 1.5em
current_text_alignment: center
current_text_width: 100%
current_data_top_margin: 10em
large_icon_top_margin: '-3.2em'
large_icon_left_position: 0px
separator_top_margin: 6em
summary_top_padding: 2em
summary_font_size: 0.8em
slot_l1: daytime_high
slot_l2: daytime_low
slot_l3: wind
slot_l4: sun_next
slot_l5: sun_following
slot_r1: humidity
slot_r2: uv_summary
slot_r3: fire_summary
slot_r4: empty
slot_r5: empty
`

and this is my weather.yaml:
`
# Download the BOM icons from https://github.com/DavidFW1960/bom_forecast/blob/master/bom_icons.zip
# and save them under <config-dir>/www/icons/bom_icons/ (Note this is for the example in the ftp component. This is different to the animated card.)
# For the animated card follow the instructions and put the icons in <config-dir>/www/icons/weather_icons. This is a DIFFERENT icon file to the above.
# Show BOM Satellite and Radar

sensor:

  - platform: template
    sensors:

      bom_current_text:
        value_template: >
            {% set val = states('sensor.murrays_run_short_text_0').split('.')[0] %} 
            {{ val | title }}

      bom_uv_alert:
        value_template: >
            UV Today: Sun Protection 
            {{ as_timestamp(states('sensor.murrays_run_uv_start_time_0')) | timestamp_custom(' %I:%M%p') | lower | replace(" 0", "") }} to {{ as_timestamp(states('sensor.murrays_run_uv_end_time_0')) | timestamp_custom(' %I:%M%p') | lower | replace(" 0", "") }}, UV Index predicted to reach {{ states('sensor.murrays_run_uv_max_index_0') }} [{{ states('sensor.murrays_run_uv_category_0') }}]
          
      bom_fire_danger:
        value_template: "Fire Danger Today: {{ states('sensor.murrays_run_fire_danger_0') }}"


# Beaufort
# https://en.wikipedia.org/wiki/Beaufort_scale
      beaufort:
        value_template: >
            {%- if states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 118 -%}
            12
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 103 -%}
            11
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 89 -%}
            10
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 75 -%}
            9
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 62 -%}
            8
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 50 -%}
            7
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 39 -%}
            6
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 29 -%}
            5
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 20 -%}
            4
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 12 -%}
            3
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 6 -%}
            2
            {%- elif states('sensor.mangrove_mountain_wind_speed_kilometre') | float  >= 2 -%}
            1
            {%- else -%}
            0
            {%- endif -%}

# Heatindex
# https://en.wikipedia.org/wiki/Heat_index
      heatindex:
        unit_of_measurement: °C
        device_class: temperature
        value_template: >
            {%- if states('sensor.mangrove_mountain_temp') | float > 27 and states('sensor.mangrove_mountain_humidity') | float > 40 -%}
            {% set T = states('sensor.mangrove_mountain_temp') | float %}
            {% set R = states('sensor.mangrove_mountain_humidity') | float %}
            {% set c1 = -8.78469475556 %}
            {% set c2 = 1.61139411 %}
            {% set c3 = 2.33854883889 %}
            {% set c4 = -0.14611605 %}
            {% set c5 = -0.012308094 %}
            {% set c6 = -0.0164248277778 %}
            {% set c7 = 0.002211732 %}
            {% set c8 = 0.00072546 %}
            {% set c9 = -0.000003582 %}
            {% set HI = c1 + (c2 * T ) + (c3 * R) + ( c4 * T * R ) + ( c5 * T**2 ) + ( c6 * R**2 ) + ( c7 * T**2 * R ) + ( c8 * T * R**2 ) + ( c9 * T**2 * R**2 ) %} 
            {{ HI | round }}
            {%- else -%}
            n/a
            {%- endif -%}
      heatindexrating:
        value_template: >
            {%- if states('sensor.heatindex') == 'n/a' -%}
            Out of range
            {%- elif states('sensor.heatindex') | float  >= 54 -%}
            Extreme danger: heat stroke imminent
            {%- elif states('sensor.heatindex') | float  >= 41 -%}
            Danger: cramps, exhaustion heat stroke probable
            {%- elif states('sensor.heatindex') | float  >= 32 -%}
            Extreme caution: cramps and exhaustion possible
            {%- elif states('sensor.heatindex') | float  >= 26 -%}
            Caution: fatigue possible
            {%- else -%}
            Normal
            {%- endif -%}

      bom_forecast_0:
        friendly_name: "Today"
        value_template: >
          {% if states('sensor.murrays_run_temp_min_0') == 'unknown' %} {% set min = states('sensor.bom_today_min') %} {% else %} {% set min = states('sensor.murrays_run_temp_min_0') %} {% endif %}
          {% if states('sensor.murrays_run_temp_max_0') == 'unknown' %} {% set max = states('sensor.bom_today_max') %} {% else %} {% set max = states('sensor.murrays_run_temp_max_0') %} {% endif %}
          {{ max|round(0)}}°/{{ min|round(0)}}°/{{states('sensor.murrays_run_rain_chance_0')|round(0)}}%
        entity_picture_template: >-
          {%- if states('sun.sun') == 'below_horizon' and (states('sensor.murrays_run_icon_descriptor_0') == 'fog' or states('sensor.murrays_run_icon_descriptor_0') == 'haze' or states('sensor.murrays_run_icon_descriptor_0') == 'hazy' or states('sensor.murrays_run_icon_descriptor_0') == 'light-showers' or states('sensor.murrays_run_icon_descriptor_0') == 'partly-cloudy' or states('sensor.murrays_run_icon_descriptor_0') == 'showers' or states('sensor.murrays_run_icon_descriptor_0') == 'shower' or states('sensor.murrays_run_icon_descriptor_0') == 'light_showers' or states('sensor.murrays_run_icon_descriptor_0') == 'light_shower' or states('sensor.murrays_run_icon_descriptor_0') == 'partly_cloudy' or states('sensor.murrays_run_icon_descriptor_0') == 'mostly_sunny') -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_0') ~ '-night.png' }}
          {%- else -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_0') ~ '.png' }}
          {%- endif -%}

      bom_forecast_1:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
          {{ date | timestamp_custom('Tomorrow (%-d/%-m)') }}
        value_template: >
          {{states('sensor.murrays_run_temp_max_1')|round(0)}}°/{{states('sensor.murrays_run_temp_min_1')|round(0)}}°/{{states('sensor.murrays_run_rain_chance_1')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_1') ~ '.png' }}

      bom_forecast_2:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.murrays_run_temp_max_2')|round(0)}}°/{{states('sensor.murrays_run_temp_min_2')|round(0)}}°/{{states('sensor.murrays_run_rain_chance_2')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_2') ~ '.png' }}

      bom_forecast_3:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.murrays_run_temp_max_3')|round(0)}}°/{{states('sensor.murrays_run_temp_min_3')|round(0)}}°/{{states('sensor.murrays_run_rain_chance_3')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_3') ~ '.png' }}

      bom_forecast_4:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.murrays_run_temp_max_4')|round(0)}}°/{{states('sensor.murrays_run_temp_min_4')|round(0)}}°/{{states('sensor.murrays_run_rain_chance_4')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_4') ~ '.png' }}

      bom_forecast_5:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.murrays_run_temp_max_5')|round(0)}}°/{{states('sensor.murrays_run_temp_min_5')|round(0)}}°/{{states('sensor.murrays_run_rain_chance_5')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_5') ~ '.png' }}

      bom_forecast_6:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.murrays_run_temp_max_6')|round(0)}}°/{{states('sensor.murrays_run_temp_min_6')|round(0)}}°/{{states('sensor.murrays_run_rain_chance_6')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.murrays_run_icon_descriptor_6') ~ '.png' }}

# ONLY USE ONE bom_today_max below:
# JK Commented Out Start #
#      bom_today_max:
#        value_template: >
#          {{ state_attr('sensor.today_temp_bom', 'max_value') }}
# JK Commented Out End #

# JK Uncommented Start #
      bom_today_max:
        value_template: >
          {%- if states('sensor.murrays_run_temp_max_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom', 'max_value') }}
          {% else %}
            {{ states('sensor.murrays_run_temp_max_0') }}
          {% endif %}
# JK Uncommented End #

# ONLY USE ONE bom_today_min below:
# JK Commented Out Start #
#      bom_today_min:
#        value_template: >
#          {{ state_attr('sensor.today_temp_bom', 'min_value') }}
# JK Commented Out End #

# JK Uncommented Start #
      bom_today_min:
        value_template: >
          {%- if states('sensor.murrays_run_temp_min_0') == 'n/a' -%} 
            {{ state_attr('sensor.today_temp_bom', 'min_value') }}
          {% else %}
            {{ states('sensor.murrays_run_temp_min_0') }}
          {% endif %}
# JK Uncommented End #


# IMPORTANT NOTE IF YOU USE average, you must comment out the below statistics sensor. Both cannot exist
# https://github.com/Limych/ha-average
#  - platform: average
#    name: today_temp_bom
#    entities:
#      - sensor.mangrove_mountain_temp
#    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
#    end: '{{ now() }}'

# IMPORTANT NOTE IF YOU USE statistics, you must comment out the above average sensor. Both cannot exist
#  - platform: statistics
#    name: today_temp_bom
#    sampling_size: 150
#    entity_id: sensor.mangrove_mountain_temp
#    max_age:
#      hours: 24

automation:
- alias: 'Update BOM Icons'
  trigger:
    - event: start
      platform: homeassistant
    - entity_id: sun.sun
      platform: state
      to: 'above_horizon'
    - entity_id: sun.sun
      platform: state
      to: 'below_horizon'
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.bom_forecast_0, sensor.bom_forecast_1, sensor.bom_forecast_2, sensor.bom_forecast_3, sensor.bom_forecast_4, sensor.bom_forecast_5, sensor.bom_forecast_6
`

**Comment by DavidFW1960** [comment]
```
      bom_current_text:
        value_template: >
            {% set val = states('sensor.murrays_run_short_text_0').split('.')[0] %} 
            {{ val | title }}
```
So this is the template.

I suspect the sensor.murrays_run_short_text_0 doesn't exit. Can you see it in dev-tools? On the basis of other entries it's probably sensor.mangrove_mountain_short_text_0 you should be using.

The BOM integration creates 2 sets of sensors. Observation ones sensor.mangrove_mountain.* and forecast ones sensor.murrays_run.* and you have used the wrong one in the template hence unknown.

**Comment by jkelly73** [comment]
Thanks David,
Your review of the template is much appreciated.

  - sensor.murrays_run_short_text_0 does exist in dev-tools, but is "unknown"
  - sensor.murrays_run_short_text_0 does not exist.

I have attached a screenshot for the state of sensor.murrays_run_short_text_0 when reviewed in dev-tools this morning.  I have also included a screenshot to show all my *mangrove_mountain* entities.
Finally, I have added a screenshot from dev-tools to show what bom_current_text shows.
![Image 24-1-2022 at 09 16](https://user-images.githubusercontent.com/85336126/150700258-ad6f6d2c-52fd-4d83-b521-5156b2bb7051.jpg)

![Image 24-1-2022 at 09 17](https://user-images.githubusercontent.com/85336126/150700268-4660ea23-16dc-4685-a944-17dde95b43bc.jpg)

![Image 24-1-2022 at 09 22](https://user-images.githubusercontent.com/85336126/150700363-1271b110-569f-45da-b0a3-ab628d617a13.jpg)

**Comment by DavidFW1960** [comment]
> * sensor.murrays_run_short_text_0 does exist in dev-tools, but is "unknown"
> * sensor.murrays_run_short_text_0 does not exist.

Ok that's contradictory info but the issue seems to be that BOM isn't publishing sensor.murrays_run_short_text_0 This can happen for some of the tinpot weather areas with BOM. If the BOM forecast info is unknown then the template won't return a real value either. if sensor.murrays_run_icon_descriptor_0 is valid you could use that instead in the template sensor like this:
```
      bom_current_text:
        value_template: >
            {% set val = states('sensor.murrays_run_icon_descriptor_0').split('.')[0] %} 
            {{ val | title }}
```
If BOM isn't publishing it there's not much you can do except maybe pick a different nearby suburb. I have a similar issue at Kariong right now where BOM doesn't publish Pressure and recently Humidity and Apparent Temp are gone as well - I hope the recent ones are a temporary glitch otherwise I can obtain them a different way but I don't wanna screw around if they are going to fix it.
