### ISSUE TITLE
Is heat index template correct?

### ISSUE THREAD

**Issue by jonwaland** [DavidFW1960/bom-weather-card#72]
Hey David,

if the current temp is <27 or humidity is <40%, the heatindex template returns N/A, and so the heatindex rating never returns Normal.

I get that the equation actually only works from 27c/40%, but shouldn't it return Normal when the rating is below 26?

**Comment by DavidFW1960** [comment]
How can it? You can't calculate a valid heat index outside the range so I return N/A. You can change the template yourself to do whatever you want it to do.

**Comment by jonwaland** [comment]
I get that the heat index equation is only valid from "26/40", but I believe the before that, the result should be "normal".

Anyway, you are right, I can change myself.
