### ISSUE TITLE
Error when render() is called before set hass(hass) (i.e. before this._hass is set)

### ISSUE THREAD

**Issue by manisar2** [DavidFW1960/bom-weather-card#73]
Thanks for giving us this super-awesome component!

There is an issue I wish to report along with a proposed solution.

I'm seeing that mostly the `render()` method is called before `set hass(hass)`.
This means that `current()` (called from render) does not have `this._hass` to work upon, so it throws an error, and prevents the rendering of the subsequent html in `render()`.

On making these two changes, my testing has shown good results.
1. In the beginning of `render()`:
    ```JavaScript
    if (!this.config || !this._hass) return html``;  // checking .config is also not a bad idea
    ```
2. With above, we want `render()` to be called again when `set hass(hass)` is called.
This can be done by _watching_ `this._hass` property, and the following getter will do that:
    ```JavaScript
    static get properties() {
      return {
        _hass: {},
        config: {},
      };
    }
    ```

**Comment by DavidFW1960** [comment]
In 3 years I have never seen this happen.. Do you want to submit a PR for this change so I can test it?

**Comment by markusg1234** [comment]
Hi David, also thanks for the great component.
I am seeing after a restart of HA the rendering stops on the companion app. A restart of the companion app is also needed.
#Manisar would this PR fix this issue?

**Comment by manisar2** [comment]
@DavidFW1960 : PR #74 on your way.
I had earlier confirmed by adding console.log() in `render()` and `set hass(hass)`.
Not always, but many a time, `render()` is getting called before the first call to `set hass(hass)`.

@markusg1234 it should, this is exactly the symptom I was seeing, except for me, it was happening on both app and Chrome.

**Comment by DavidFW1960** [comment]
Ok I've merged that into master. If you use HACS just pull master for now. I'll bump the version and in a few days if you both (and I) have no issues I'll do a release

**Comment by DavidFW1960** [comment]
It will show 0.93 as version in console.

**Comment by manisar2** [comment]
Thanks @DavidFW1960, I've downloaded and started using beta (v0.93) - results are as expected.
Shall update you if I see any issues.

Note: As I'm using a colored background, I can see when `render()` is called before `set hass(hass)` on page refreshes - when this happens, an empty card with almost zero height is painted (see below) for a split second and then the full card loads.
Before this change, the full card was never loaded in such cases.

![image](https://user-images.githubusercontent.com/23711188/154827102-625ed59d-ddac-4548-8eee-ac7ad6161c5d.png)

**Comment by DavidFW1960** [comment]
ok. I wonder if some change in HA caused that. As I said I have never seen it on Chrome or in the mobile app either.

**Comment by manisar2** [comment]
I'm scratching my head to find why this has started happening, but to no avail so far.
I've been using your card for a few days now and I saw this only recently (but persistently since then).

On another note, if this works, we may (just may) get rid of `interval` and `doRefresh` I guess later.
This is because with `this._hass` being watched, `render()` will be called anyway with the new value of `this._hass` whenever it is modified (via `set hass(hass)`).

**Comment by markusg1234** [comment]
Thankyou, it has fixed my issue.
Regards,
Markus

**Comment by DavidFW1960** [comment]
> On another note, if this works, we may (just may) get rid of `interval` and `doRefresh` later.
> 
> This is because with `this._hass` being watched, `render()` will be called anyway with the new value of `this._hass` whenever it is modified (via `set hass(hass)`).
> 
> 

Open to that
