### ISSUE TITLE
Card doesn't use correct decimal separator

### ISSUE THREAD

**Issue by bieniu** [DavidFW1960/bom-weather-card#75]
I use Polish as default language for HA, with this language decimal separator should be `,`, not `.`.

Last version without this issue: 0.90a

![image](https://user-images.githubusercontent.com/478555/157720773-a4a393e7-d087-4d3b-8f00-aa7be222683b.png)

**Comment by DavidFW1960** [comment]
Bloody hell. I'll take a loo at this.

**Comment by DavidFW1960** [comment]
Seems to have gotten screwed up when I tried to correct the decimal places. Should be a relatively easy fix... working on it but my dev instance of HA crapped itself so rebuilding a new VM for it

**Comment by DavidFW1960** [comment]
@makin-things Simon are you able to look at this?
I have tried similar to this:
```
${(Number(this._hass.states[this.config.entity_daytime_high].state).toFixed(1)).toLocaleString("pl-PL")}
```
to hard code for Polish as a test but it's ignoring it.

If I use this
```
<!DOCTYPE html>
<html>
<body>

<h2>JavaScript Dates</h2>

<p>toLocaleString() returns a date as a string, using locale settings:</p>

<p id="demo"></p>

<script>
d = 1000.94;
let text = (Number(d.toFixed(1)).toLocaleString("pl-PL"));
document.getElementById("demo").innerHTML = text;
</script>

</body>
</html>
```
as the entry at https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_tolocalestring it is working fine so I don't understand what I am doing wrong. Any ideas?

**Comment by DavidFW1960** [comment]
Thanks mate. So fiddly. That's why I originally used Number because it was returning a string and a console error. I didn't realise toFixed converted a number to a string. I'll give that a try now.

**Comment by DavidFW1960** [comment]
```
Number(Number(this._hass.states[this.config.entity_daytime_high].state).toFixed(1)).toLocaleString("pl-PL")
Number(this._hass.states[this.config.entity_daytime_high].state.toFixed(1)).toLocaleString("pl-PL")
```
Tried both those still doesn't work

**Comment by DavidFW1960** [comment]
No idea why this is happening. I ended up using parseFloat function instead and eventually made it work. Fingers crossed.

> Last version without this issue: 0.90a

Sorry about this happening. Just drafted a fix as 0.94. Please let me know if it's working for you.

**Comment by bieniu** [comment]
Looks good 👍

![image](https://user-images.githubusercontent.com/478555/159273780-a891bee5-a6fa-45d2-81ad-416f6fe21457.png)

**Comment by DavidFW1960** [comment]
Would you mind checking the latest master of this before I release the beta tomorrow.

**Comment by bieniu** [comment]
`master` looks good 👍

![image](https://user-images.githubusercontent.com/478555/165056886-11e12c00-4a2b-498f-be94-45169d8535cb.png)

**Comment by Makin-Things** [comment]
@bieniu also if your pressure sensor has more accuracy you can also set show_decimals_pressure: 1 (or 2 or 3) to have that show on the card. It should also used the correct symbols for your locale.

**Comment by Makin-Things** [comment]
@bieniu can I ask what os/browser you are using? One of the changes the was made was to fix the start of the right hand column in the middle of the card to stop it bouncing around when the width of the column changes. The image shows where it should align (excuse the poor image editing skills).
![image](https://user-images.githubusercontent.com/91187456/165067777-fdba3863-9e9c-44a0-acbf-d0894b76051e.png)

**Comment by Makin-Things** [comment]
Or it could be a caching thing and the new version hasn't been loaded yet?

**Comment by bieniu** [comment]
> One of the changes the was made was to fix the start of the right hand column in the middle of the card to stop it bouncing around when the width of the column changes

After rebooting HA, the right column has moved:

![image](https://user-images.githubusercontent.com/478555/165080352-fc6fc3c1-4fc2-4283-9776-b927020c7785.png)

IMO now it looks terrible.

**Comment by bieniu** [comment]
> if your pressure sensor has more accuracy you can also set show_decimals_pressure

I really don't like decimal places for pressure value 😉

**Comment by Makin-Things** [comment]
Awesome, thanks for the feedback.

**Comment by DavidFW1960** [comment]
> IMO now it looks terrible.

Is that a joke? You don't like the right column starting left justified from the center?

**Comment by bieniu** [comment]
No, it's not a joke, I don't like it. Sorry 🤷‍♂️

**Comment by andriej** [comment]
I agree with @bieniu , look & feel dropped. 
It was looking smooth with column go the right :)

**Comment by DavidFW1960** [comment]
Hey @Makin-Things Simon can we make this a flag?

**Comment by DavidFW1960** [comment]
Ok we will make a flag
```
make_my_card_ugly: true
```
Must say I'm surprised anyone prefers the old way but we aim to please. Expect 1.01 beta later today

**Comment by DavidFW1960** [comment]
Ok pull master and add this flag to show the old columns. 

We also removed the pressure unit flag as we can read this from the entity. Ill do the release tomorrow it this all works ok. Let me know. 
The flag is

use_old_column_format: true

**Comment by DavidFW1960** [comment]
No problems. I do try not to piss people off particularly when I broke it previously so thanks for testing and your feedback.
