### ISSUE TITLE
Google Cast: Show lovelace view Call Service - Card Blank

### ISSUE THREAD

**Issue by aquavass** [DavidFW1960/bom-weather-card#76]
Hi David,

Firstly thank you for creating the BOM custom card as I believe it is fantastic and well polished, I love the way it is presented... excellent work mate!

I have an issue I was hoping you can help me out which relates to the latest HA update providing the new "Google Cast: Show lovelace view" under Call Service... although the card shows perfectly on my PC, when I cast it to a Chromecast device it's blank. This relates to both the "type: custom:bom-weather-card" and "type: custom:bom-radar-card".

I may be doing something wrong here, are you able to advise?

Many Thanks,
John

**Comment by DavidFW1960** [comment]
Hi John,

Many many (maybe a couple of years) months ago when cast first was released, the card worked fine but then there was a HA change and I needed to change a path in the card to make the icons work. Shortly after that, I couldn't get cast to even work AT ALL for any view. After 2022.3.x came out I see cast is again working here but also saw that the weather card isn't working. As you say works on chrome but not chromecast. I have no idea why it's not working on Chromecast. Might be some kind of HA frontend issue with cast... I will ask the devs about this on discord but I have no clue what might be causing this to happen.

**Comment by DavidFW1960** [comment]
Just a heads up... there's an update coming for the card that will fix this cast issue

**Comment by aquavass** [comment]
Awesome you're a legend... Thanks David!

**Comment by DavidFW1960** [comment]
Try pulling master. It has the fix. I just need to add some doco before I release it.
