### ISSUE TITLE
Card forcing horizontal scroll

### ISSUE THREAD

**Issue by grastraa** [DavidFW1960/bom-weather-card#78]
I noted another closed issue similar to this, however my companion app wasn't effected in the same way and the user reported it working on PC fine, so I can't be sure it's the same issue. 

I am using a vertical stack (as it appears the card nests within one as default), and I have copied the full template from this repo for set up for the first three issues just to rule anything funky out that I may have inadvertently changed.

This issue has been present since I started using it some time late last year.

Android companion app before scrolling:
![image](https://user-images.githubusercontent.com/67679349/159067513-cf215c11-54fb-4007-9620-89d249c7104c.png)

Android companion app after horizontal scrolling:
![image](https://user-images.githubusercontent.com/67679349/159067377-c6714a81-8c08-4e15-9acc-8ec54f7676af.png)

Firefox horizontal scroll bar when window is set to a width smaller than 442:
![image](https://user-images.githubusercontent.com/67679349/159067194-26d70fbd-9d6e-4b83-b72a-1763bb072088.png)

Issue also present when using popup cards (removing bom-weather-card solves this), it also effects other cards in the vertical stack:
![image](https://user-images.githubusercontent.com/67679349/159067774-c9d8f194-504b-4f93-bf14-7148ef23ef3b.png)
This is a screenshot of firefox also, but is also present on popup cards in the android app. 

The issue is still present when popup cards are expanded to full width:
![image](https://user-images.githubusercontent.com/67679349/159070870-7374a89b-010c-4d2f-a06d-b0a9d3b7fffd.png)

On chrome on a width smaller than 442 I have no ability to horizontal scroll, but information is cut off. This also effects other cards displayed in vertical stack, as shown in the second image here:
![image](https://user-images.githubusercontent.com/67679349/159068705-d1bff81d-45c1-43e1-95c8-f119e2f03ce8.png)
![image](https://user-images.githubusercontent.com/67679349/159068901-890499ae-6d22-4d1b-869c-f9aeca44ebc6.png)

Popup cards in chrome behave slightly differently, displaying all cards within the vertical stack with plenty of space either side, however this card still produces horizontal scroll bars for some reason:
![image](https://user-images.githubusercontent.com/67679349/159069304-db4a2060-3be5-4293-9659-7ec0a05d9259.png)

**Comment by DavidFW1960** [comment]
I have not seen it do this on chrome/firefox on PC or MAC and iOS App. What other cards do you use?

**Comment by DavidFW1960** [comment]
I'm thinking maybe your theme is forcing a width?

**Comment by grastraa** [comment]
Occurs on default theme also. 
It occurs when this is the only card on a dashboard, of the many cards I have used, only this card produces this behaviour.

Out of curiousity, did you test by setting chrome/firefox window width to 441 or smaller on PC?

**Comment by DavidFW1960** [comment]
I know this is frustrating for you but I have no other reports of this in 3(?) years and I can't duplicate it either. It seems something specific to you.

![image](https://user-images.githubusercontent.com/36390762/159187870-b01a1174-6e7c-425c-b840-0853b148af3a.png)
![image](https://user-images.githubusercontent.com/36390762/159187895-8de1ee33-461c-427e-90d3-ea1c55db0324.png)

**Comment by grastraa** [comment]
Thanks a bunch for verifying that for me. Guess it's time to one by one check my countless custom integrations.
