### ISSUE TITLE
Implementation with OpenWeatherMap sensors

### ISSUE THREAD

**Issue by MiOiM** [DavidFW1960/bom-weather-card#79]
Hi David.

Is it possible to use OpenWeatherMap sensors with CAWC?

I'm getting the following sensors from OWM, but I don't think they meet the minimum required by CAWC:

```
- sensor.openweathermap_cloud_coverage
- sensor.openweathermap_condition
- sensor.openweathermap_dew_point
- sensor.openweathermap_feels_like_temperature
- sensor.openweathermap_forecast_cloud_coverage
- sensor.openweathermap_forecast_condition
- sensor.openweathermap_forecast_precipitation
- sensor.openweathermap_forecast_precipitation_probability
- sensor.openweathermap_forecast_pressure
- sensor.openweathermap_forecast_temperature
- sensor.openweathermap_forecast_temperature_low
- sensor.openweathermap_forecast_time
- sensor.openweathermap_forecast_wind_bearing
- sensor.openweathermap_forecast_wind_speed
- sensor.openweathermap_humidity
- sensor.openweathermap_wind_speed
- sensor.openweathermap_wind_bearing
- sensor.openweathermap_weather_code
- sensor.openweathermap_weather
- sensor.openweathermap_uv_index
- sensor.openweathermap_temperature
- sensor.openweathermap_snow
- sensor.openweathermap_rain
- sensor.openweathermap_pressure
- sensor.openweathermap_precipitation_kind
```

Thanks

**Comment by DavidFW1960** [comment]
The card doesn't care what the weather source is as long as they provide the required information. Does it provide forecasts for 6 days etc?

**Comment by MiOiM** [comment]
It does, but not in single sensors. 
There is an entity `weather.openweathermap` which show the forecast for 5 days, but I cannot find the way to use it in CAWC

**Comment by DavidFW1960** [comment]
well you can use it if you extract the data from the weather entity using template sensors. That's pretty straightforward. If you post the weather entity from dev-tools I'll do one for you that you can use to make the rest.
