### ISSUE TITLE
UV_summary not displaying

### ISSUE THREAD

**Issue by LastElf** [DavidFW1960/bom-weather-card#80]
Relevant code and screenshot below, can't see anything wrong with my yaml unless there's a weird order of operations thing going on, but all the others are working:

Home Assistant 2022.3.5 in Docker
Card version: 0.94

### Card
```
entity_uv_summary: sensor.bom_uv_formatted
...
slot_r1: pop
slot_r2: humidity
slot_r3: uv_summary
slot_r4: fire_summary
slot_r5: remove
```

![image](https://user-images.githubusercontent.com/6188342/162078957-aa09a387-4fd6-4a38-81cc-2ce1a6bccd22.png)

### Sensor template
```
    - name: bom_uv_formatted
      state: >
        {{ states('sensor.bundamba_uv_category_0') | replace('veryhigh', 'Very High') | title }}
```

![image](https://user-images.githubusercontent.com/6188342/162079334-8f1457e3-e59f-4328-991c-5fb0ce461568.png)

**Comment by DavidFW1960** [comment]
The devil is always in the detail:
```
            entity_uv_alert: sensor.bom_uv_alert
            entity_uv_alert_summary: sensor.uv_cat_formatted
```
You probably meant this:
```
entity_uv_alert: sensor.bom_uv_formatted
```

**Comment by LastElf** [comment]
For the record: uv_alert_summary was what I needed in both the slot and the entity (For anyone else that finds this thread)

@DavidFW1960 I was basing this on the Slots and Flags section of your code readme. The Configuration example uses the new uv_alert values but the references below are still showing an old variable name and need to be updated. That's where my confusion came from. Thanks for the quick response!

**Comment by DavidFW1960** [comment]
it actually uses a summary variable for the summary text and the alert variable for the slot. so it uses both. if you don't provide a variable as it's optional it will just be blank.
