### ISSUE TITLE
Sunrise / sunset icons incorrect after data update

### ISSUE THREAD

**Issue by TheCranston** [DavidFW1960/bom-weather-card#81]
David,
I'm doing an NWS connection for the data source.  At least twice a day they update the sun rise and sun set data points.  The card updates the data correctly, however the icons lag for some indeterminate amount of time.  The display shows the sundown icon next to the next sun rise time, and the same for the sun up icon - next to the next sun down time.  If I manually refresh the page the icons correct themselves.  At some point, and I've not been able to characterize the amount of time, the icons will sync correctly.  But, alas, for some time period they are clearly incorrect.  I'm not sure how to correct it in the javascript, or I'd offer a PR to that effect.

Here is an image of the icons incorrect:
![IMG_2870](https://user-images.githubusercontent.com/3859141/163453451-b88d8ac5-1915-4eb5-a2fd-0dd9a38eec81.jpg)

Here is an image after hitting refresh showing the icons in the correct locations:
![IMG_2871](https://user-images.githubusercontent.com/3859141/163453465-16c42a45-eacd-4e2c-8612-e123144af53f.jpg)

**Comment by DavidFW1960** [comment]
Im away over Easter. Will get back to you in a week

**Comment by DavidFW1960** [comment]
This should be fixed now with the latest PR

**Comment by TheCranston** [comment]
I can confirm that the latest PR fixed the icons.  They are now tracking the updated data for sun rise and sun set.  Thanks!!!
