### ISSUE TITLE
BOM forecast weird indentation

### ISSUE THREAD

**Issue by jurgenweber** [DavidFW1960/bom-weather-card#84]
Hi @DavidFW1960 

I noticed just recently that darksky is on the way out, maybe. So I figured it was time to find something else. After traveling around and finding tomorrow.io and openweathermap they just didn't have the same detail as my current darksky. I finally today, found your card here and then the new bureau_of_meteorology custom component... amazing. Love it.

So I am following your readme and I maybe it needs some updating because I am just doing  some serious copy and pasting.

So firstly:

![image](https://user-images.githubusercontent.com/3013734/164446625-b4ef87a4-ec9a-465f-b5ec-fca7b8b5561d.png)

Do these sensors that are showing rubbish/Nan/unkown just need some time to update? Do they have a large period between updates?

Lastly and the main one, when doing your minmal card/BOM Forecast.. I have this weird indentation on the final day:

![image](https://user-images.githubusercontent.com/3013734/164446785-af5821d0-1275-4695-ba47-c6f82e5e7fad.png)

I am using current HASS core on Debian (2022.4.6).

Lastly and weirdly, I also live in Kariong (not too far from Mitch and Lang). :)

**Comment by DavidFW1960** [comment]
Well I love the easy ones...
The minimal card requires card-mod to style the conditional card. Do you have that installed?
The NaN is because you havent configured the templates and/or the average or statistics to populate them. Check the stated for entities you are parsing in dev-tools to make sure they are all valid.

Karion too??? It's a small world

**Comment by jurgenweber** [comment]
> The minimal card requires card-mod to style the conditional card. Do you have that installed?

No, installing.... fixed.

> The NaN is because you havent configured the templates and/or the average or statistics to populate them. Check the stated for entities you are parsing in dev-tools to make sure they are all valid.

so I have this

```
- platform: average
  name: today_temp_bom
  entities:
    - sensor.gosford_temp
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
```
and then under my template sensors

```
    bom_today_max:
      value_template: >
        {{ state_attr('sensor.today_temp_bom', 'max_value') }}

    bom_today_min:
      value_template: >
        {{ state_attr('sensor.today_temp_bom', 'min_value') }}
```  
sensor.gosford_temp exists and is cool:
![image](https://user-images.githubusercontent.com/3013734/164624754-7052bf03-15ef-4414-acbd-db060e86d5c4.png)

but for some reason; 
![image](https://user-images.githubusercontent.com/3013734/164624835-82123379-fdf8-43ee-b114-cae84e0826fc.png)

isn't there.....

> Kariong too??? It's a small world

craziness. :)

**Comment by jurgenweber** [comment]
it just dawned on me, I am missing https://github.com/Limych/ha-average/

**Comment by jurgenweber** [comment]
boom, there we go.. nothing but pebcak!

Thanks for the hints! Love your work! I am sure we will run into each other one day!
