### ISSUE TITLE
Average calculation failing for today_temp_bom

### ISSUE THREAD

**Issue by colinlandsmeer** [DavidFW1960/bom-weather-card#97]
Hi David
I'm having issue with today_temp_bom showing unavailable - which affects bom_today_max & min sensors on card
![image](https://user-images.githubusercontent.com/65805961/171997489-bfff96f4-12f8-4c72-b8df-23651819f16c.png)

Both the Bureau of Meteorology & Average Sensor components have been reinstalled via HACS (with reboots as part of process)
Bureau of Meteorology (bremor) v1.1.8 
Average Sensor (limych) v2.2.3 
I have copied your latest Weather.yaml (have only updated location names - otherwise using default options) & bom-weather-card.js.
All other items appear to be working ok
In HA error log - i'm getting this error

    2022-06-04 21:08:52 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.today_temp_bom fails
    Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
    File "/config/custom_components/average/sensor.py", line 301, in async_update
    await self._async_update_state()
    File "/config/custom_components/average/sensor.py", line 479, in _async_update_state
    history_list = await get_instance(self.hass).async_add_executor_job(
    NameError: name 'get_instance' is not defined

Any assistance would be appreciated, thanks Colin

**Comment by DavidFW1960** [comment]
There was an update for average because HA did break it. Whice HA are you using? Tou can always switch to using statistics instead but average is fixed and working. Check that HACS downloaded ut correctly

**Comment by colinlandsmeer** [comment]
apologies for not including that info
I'm running HA Core-2022.2.9 (as Docker container)
Yes - the HACS download of Average component appears ok
i have switched to using statistics instead (& update values in lovelace config)
Thanks for your assistance/advice

**Comment by DavidFW1960** [comment]
I'm wondering if the fix for average requires a later home assistant? Maybe look in the repo for average and log an issue there. The author is in Russia though and is having internet access issues. All I can say here is that average is working perfectly for me since it was fixed a few weeks ago.
