### ISSUE TITLE
bom_today_max and bom_today_min template sensors

### ISSUE THREAD

**Issue by ozmutley** [DavidFW1960/bom-weather-card#99]
I have found that the value that the BoM integration is returning for any missing forecasted temps is **'unknown'** instead of **'n/a'** which was causing a problem when using the alternate code blocks for the **bom_today_max** and **bom_today_min** templates in the _weather.yaml_ file.
The result was the L1 and L2 slots were showing `Today's High NaN°C` and `Today's Low NaN°C`.
After changing the comparator values to **'unknown'**, the two slots are now correctly showing the calculated min/max (or the forecasted min/max once a valid value was returned from the BoM integration)

**Comment by DavidFW1960** [comment]
Thanks. Ill take a look tomorrow

**Comment by DavidFW1960** [comment]
OK I see in templates.md, readme.md and weather.yaml package that I am looking for unknown not n/a therefore if BOM Integration is returning unknown it should be correct. Can you check your weather.yaml file agrees with the repo? I do remember changing this recently.

**Comment by ozmutley** [comment]
Looking at the weather.yaml file in the repo, lines 170-176 show
```
#      bom_today_max:
#        value_template: >
#          {%- if states('sensor.kariong_temp_max_0') == 'n/a' -%} 
#            {{ state_attr('sensor.today_temp_bom', 'max_value') }}
#          {% else %}
#            {{ states('sensor.kariong_temp_max_0') }}
#          {% endif %}
```
and lines 183-189 show
```
#      bom_today_min:
#        value_template: >
#          {%- if states('sensor.kariong_temp_min_0') == 'n/a' -%} 
#            {{ state_attr('sensor.today_temp_bom', 'min_value') }}
#          {% else %}
#            {{ states('sensor.kariong_temp_min_0') }}
#          {% endif %}
```

I had to change my weather.yaml file to look for the `unknown` value instead of the `n/a` as listed above

Apologies if I'm looking in the wrong spot, but when I view the templates.md file in the repo, it also still shows the ```#          {%- if states('sensor.kariong_temp_min_0') == 'n/a' -%}``` line

**Comment by ozmutley** [comment]
OK - after looking through the weather.yaml file I can see that you have changed the `n/a` to `unknown` within the **bom_forecast_0** template sensor (lines 101 & 102), however the commented out alternative blocks for **bom_today_min** and **bom_today_max** have still got `n/a` (lines 172 & 185)
These may have been missed when you updated the other ones as they were commented out

**Comment by DavidFW1960** [comment]
ok I think I fixed those as well now. Can you check they all look right and close this issue? Thanks for the report

**Comment by ozmutley** [comment]
Yep, everything looks good. Will close this issue now.
